namespace ParaTool.Core.Schema;

/// <summary>
/// Human-readable EN+RU labels for BG3 condition functions and surface types.
/// Used by ConditionBlocksEditor to show friendly names instead of raw function names.
/// </summary>
public static class ConditionLabels
{
    // ═══════════════════════════════════════════════════════════
    // CONDITION FUNCTION LABELS — (English, Russian)
    // Covers: HardcodedConditions.lua + CommonConditions.khn +
    //         CommonConditionsDev.khn + amp_conditions.khn
    // ═══════════════════════════════════════════════════════════

    public static readonly Dictionary<string, (string En, string Ru)> Functions = new(StringComparer.OrdinalIgnoreCase)
    {
        // ── Target ────────────────────────────────────────────
        ["Enemy"] = ("Is Enemy", "Враг"),
        ["Ally"] = ("Is Ally", "Союзник"),
        ["Self"] = ("Is Self", "Это вы"),
        ["Party"] = ("Party Member", "Член группы"),
        ["Player"] = ("Is Player", "Игрок"),
        ["Summon"] = ("Is Summon", "Призванное существо"),
        ["SummonOwner"] = ("Is Summon Owner", "Владелец призыва"),
        ["Character"] = ("Is Character", "Персонаж"),
        ["Item"] = ("Is Item", "Предмет"),
        ["CrowdCharacter"] = ("Is Crowd NPC", "Массовка (NPC)"),

        // ── Combat ────────────────────────────────────────────
        ["Combat"] = ("In Combat", "В бою"),
        ["TurnBased"] = ("Turn-Based Mode", "Пошаговый режим"),
        ["ActedThisRoundInCombat"] = ("Acted This Round", "Действовал в этом раунде"),
        ["HadTurnInCombat"] = ("Had Turn in Combat", "Уже ходил в бою"),
        ["AreInSameCombat"] = ("In Same Combat", "В одном бою"),
        ["IsCurrentTurnInCombat"] = ("Is Current Turn", "Сейчас его ход"),
        ["IsInCombatWithHostilePartyMember"] = ("Fighting Party", "Воюет с группой"),

        // ── State ─────────────────────────────────────────────
        ["Dead"] = ("Is Dead", "Мёртв"),
        ["IsDowned"] = ("Is Downed", "В нокауте"),
        ["LethalHP"] = ("Lethal HP", "Смертельное HP"),
        ["FreshCorpse"] = ("Fresh Corpse", "Свежий труп"),
        ["Immobilized"] = ("Immobilized", "Обездвижен"),
        ["IsMoving"] = ("Is Moving", "Движется"),
        ["IsMovable"] = ("Is Movable", "Можно двигать"),
        ["CanMove"] = ("Can Move", "Может двигаться"),
        ["IsConcentrating"] = ("Concentrating", "Концентрируется"),
        ["Locked"] = ("Is Locked", "Заперт"),
        ["IsFloating"] = ("Is Floating", "Парит"),
        ["Grounded"] = ("Grounded", "На земле"),
        ["IsUnimportant"] = ("Is Unimportant", "Неважный"),
        ["IsProxy"] = ("Is Proxy", "Прокси"),
        ["IsSentient"] = ("Is Sentient", "Разумный"),
        ["IsLivingBeing"] = ("Is Living", "Живое существо"),
        ["IsInorganic"] = ("Is Inorganic", "Неорганический"),
        ["IsSneakingOrInvisible"] = ("Sneaking/Invisible", "Крадётся/невидим"),
        ["IsOnFire"] = ("On Fire", "Горит"),
        ["IsCrowdControlled"] = ("Crowd Controlled", "Под контролем"),
        ["IsKillingBlow"] = ("Killing Blow", "Смертельный удар"),

        // ── Status ────────────────────────────────────────────
        ["HasStatus"] = ("Has Status", "Имеет статус"),
        ["StatusId"] = ("Status Is", "Статус равен"),
        ["HasAnyStatus"] = ("Has Any Status", "Есть любой статус"),
        ["IsImmuneToStatus"] = ("Immune to Status", "Иммунитет к статусу"),
        ["StatusHasStatusGroup"] = ("Status in Group", "Статус в группе"),
        ["HasExtendableStatus"] = ("Has Extendable Status", "Есть продлеваемый статус"),
        ["PassiveHasStatus"] = ("Passive Has Status", "Пассивка имеет статус"),
        ["SpellHasStatus"] = ("Spell Has Status", "Заклинание имеет статус"),
        ["IsGameplayStatus"] = ("Is Gameplay Status", "Игровой статус"),
        ["IsStatusEvent"] = ("Is Status Event", "Событие статуса"),
        ["IsStatusFromOther"] = ("Status From Other", "Статус от другого"),
        ["IsStatusFromSelf"] = ("Status From Self", "Статус от себя"),
        ["HasBurningStatus"] = ("Is Burning", "Горит"),
        ["IsShockedOrSimilar"] = ("Shocked/Similar", "В шоке и т.п."),
        ["HasHexStatus"] = ("Has Hex", "Под Сглазом"),
        ["HasHuntersMark"] = ("Has Hunter's Mark", "Метка охотника"),
        ["HasHeatMetalActive"] = ("Heat Metal Active", "Раскалённый металл"),

        // ── Attack ────────────────────────────────────────────
        ["IsWeaponAttack"] = ("Weapon Attack", "Атака оружием"),
        ["IsMeleeAttack"] = ("Melee Attack", "Ближняя атака"),
        ["IsRangedWeaponAttack"] = ("Ranged Weapon Attack", "Дальняя атака оружием"),
        ["IsRangedAttack"] = ("Ranged Attack", "Дальняя атака"),
        ["IsMeleeWeaponAttack"] = ("Melee Weapon Attack", "Ближняя атака оружием"),
        ["IsSpellAttack"] = ("Spell Attack", "Атака заклинанием"),
        ["IsMeleeSpellAttack"] = ("Melee Spell Attack", "Ближняя магическая атака"),
        ["IsRangedSpellAttack"] = ("Ranged Spell Attack", "Дальняя магическая атака"),
        ["IsUnarmedAttack"] = ("Unarmed Attack", "Безоружная атака"),
        ["IsMeleeUnarmedAttack"] = ("Melee Unarmed", "Ближняя безоружная"),
        ["IsRangedUnarmedAttack"] = ("Ranged Unarmed", "Дальняя безоружная"),
        ["IsAttack"] = ("Is Attack", "Это атака"),
        ["IsMainHandAttack"] = ("Main Hand Attack", "Основная рука"),
        ["IsOffHandAttack"] = ("Off Hand Attack", "Вторая рука"),
        ["IsReactionAttack"] = ("Reaction Attack", "Атака реакцией"),
        ["IsThrowAttackRoll"] = ("Throw Attack", "Атака броском"),
        ["AttackingWithMeleeWeapon"] = ("Attacking Melee", "Атакует ближним"),
        ["AttackingWithRangedWeapon"] = ("Attacking Ranged", "Атакует дальним"),
        ["AMP_IsMeleeMainHandAttack"] = ("AMP: Melee Main Hand", "AMP: Ближняя основная"),
        ["AMP_IsMercenaryWeaponAttack"] = ("AMP: Mercenary Attack", "AMP: Наёмничья атака"),
        ["AMP_IsRangedWeaponAttack"] = ("AMP: Ranged Attack", "AMP: Дальняя атака"),

        // ── Roll ──────────────────────────────────────────────
        ["IsCritical"] = ("Critical Hit", "Критический удар"),
        ["IsHit"] = ("Is Hit", "Попадание"),
        ["IsMiss"] = ("Miss", "Промах"),
        ["IsCriticalMiss"] = ("Critical Miss", "Критический промах"),
        ["HasAdvantage"] = ("Has Advantage", "С преимуществом"),
        ["HasDisadvantage"] = ("Has Disadvantage", "С помехой"),
        ["TargetHasAdvantage"] = ("Target Has Advantage", "Цель с преимуществом"),
        ["TargetHasDisadvantage"] = ("Target Has Disadvantage", "Цель с помехой"),
        ["SavingThrow"] = ("Saving Throw", "Спасбросок"),
        ["SkillCheck"] = ("Skill Check", "Проверка навыка"),
        ["AbilityCheck"] = ("Ability Check", "Проверка характеристики"),
        ["RollDieAgainstDC"] = ("Roll vs DC", "Бросок против КС"),
        ["RollDieAgainstPercent"] = ("Roll vs Percent", "Бросок против %"),
        ["RollDieEqualsTo"] = ("Roll Equals", "Бросок равен"),
        ["IsSavingThrow"] = ("Is Saving Throw", "Это спасбросок"),

        // ── Spell ─────────────────────────────────────────────
        ["IsSpell"] = ("Is Spell", "Заклинание"),
        ["IsCantrip"] = ("Is Cantrip", "Заговор"),
        ["SpellId"] = ("Spell Is", "Заклинание равно"),
        ["IsSpellOfSchool"] = ("Spell of School", "Школа магии"),
        ["IsLeveledSpell"] = ("Is Leveled Spell", "Левельное заклинание"),
        ["IsLeveledSpellStrict"] = ("Leveled Spell (strict)", "Левельное (строго)"),
        ["SpellTypeIs"] = ("Spell Type Is", "Тип заклинания"),
        ["SpellCategoryIs"] = ("Spell Category", "Категория заклинания"),
        ["HasSpellFlag"] = ("Has Spell Flag", "Флаг заклинания"),
        ["IsSpellLevel"] = ("Spell Level Is", "Уровень заклинания"),
        ["SpellDamageTypeIs"] = ("Spell Damage Type", "Тип урона заклинания"),
        ["IsSpellChildOrVariantFromContext"] = ("Spell Child/Variant", "Вариант заклинания"),
        ["IsSpellIdOrChild"] = ("Spell or Child", "Заклинание или вариант"),
        ["IsSpellAttack"] = ("Spell Attack", "Магическая атака"),
        ["HasCantripSpellLevel"] = ("Cantrip Level", "Уровень заговора"),
        ["HasSpellSpellLevel"] = ("Spell Level", "Уровень заклинания"),
        ["IsSpellSchool"] = ("Spell School", "Школа магии"),
        ["IsFireMasterySpell"] = ("Fire Mastery Spell", "Заклинание огня"),
        ["IsTeleportSpell"] = ("Teleport Spell", "Телепортация"),
        ["IsMovementSpell"] = ("Movement Spell", "Заклинание перемещения"),
        ["IsHideSpell"] = ("Hide Spell", "Заклинание укрытия"),
        ["IsForceSpell"] = ("Force Spell", "Силовое заклинание"),
        ["IsDivineSmite"] = ("Divine Smite", "Божественная кара"),
        ["IsDivineStrike"] = ("Divine Strike", "Божественный удар"),
        ["IsEldritchBlast"] = ("Eldritch Blast", "Мистический заряд"),
        ["IsGuidingBolt"] = ("Guiding Bolt", "Направляющий снаряд"),
        ["IsFireball"] = ("Fireball", "Огненный шар"),
        ["IsChainLightning"] = ("Chain Lightning", "Цепная молния"),
        ["IsChillTouch"] = ("Chill Touch", "Леденящее прикосновение"),
        ["IsShockingGrasp"] = ("Shocking Grasp", "Шоковая хватка"),
        ["IsNecroNuke"] = ("Necro Nuke", "Некро-взрыв"),
        ["IsSneakAttack"] = ("Sneak Attack", "Скрытая атака"),
        ["IsSeluneSpell"] = ("Selûne Spell", "Заклинание Селуне"),
        ["IsSpiritualWeaponSpell"] = ("Spiritual Weapon", "Духовное оружие"),
        ["IsRevivifySpell"] = ("Revivify", "Оживление"),
        ["IsLayOnHandsSpell"] = ("Lay on Hands", "Наложение рук"),
        ["IsPerformSpell"] = ("Perform", "Выступление"),
        ["IsDash"] = ("Is Dash", "Рывок"),
        ["IsBreathWeapon"] = ("Breath Weapon", "Оружие дыхания"),
        ["HasAttackRoll"] = ("Has Attack Roll", "Есть бросок атаки"),
        ["HasAoEConditions"] = ("Has AoE", "Имеет область"),
        ["SpellActivations"] = ("Spell Activations", "Активации заклинания"),

        // ── Equipment ─────────────────────────────────────────
        ["HasShieldEquipped"] = ("Has Shield", "Есть щит"),
        ["WearingArmor"] = ("Wearing Armor", "В броне"),
        ["IsEquipped"] = ("Is Equipped", "Экипирован"),
        ["HasWeaponProperty"] = ("Weapon Property", "Свойство оружия"),
        ["WieldingWeapon"] = ("Wielding Weapon", "Держит оружие"),
        ["Unarmed"] = ("Unarmed", "Безоружен"),
        ["IsWeapon"] = ("Is Weapon", "Это оружие"),
        ["IsImprovisedWeapon"] = ("Improvised Weapon", "Импровизированное оружие"),
        ["EquipmentSlotIs"] = ("Equipment Slot", "Слот экипировки"),
        ["IsInActiveWeaponSet"] = ("Active Weapon Set", "Активный набор оружия"),
        ["HasProficiency"] = ("Has Proficiency", "Владеет"),
        ["IsOfProficiencyGroup"] = ("Proficiency Group", "Группа владения"),
        ["HasProficiencyBonus"] = ("Proficiency Bonus", "Бонус владения"),
        ["IsWeaponOfProficiencyGroup"] = ("Weapon Prof. Group", "Оружие по группе"),
        ["IsProficientWith"] = ("Proficient With", "Владеет оружием"),
        ["IsProficientWithEquippedWeapon"] = ("Proficient w/ Equipped", "Владеет экипированным"),
        ["HasInstrumentTypeEquipped"] = ("Instrument Equipped", "Инструмент экипирован"),
        ["IsAnInstrumentRequired"] = ("Instrument Required", "Нужен инструмент"),
        ["HasInstrumentEquipped"] = ("Has Instrument", "Есть инструмент"),
        ["NoInstrumentEquipped"] = ("No Instrument", "Нет инструмента"),
        ["DualWielder"] = ("Dual Wielder", "Двуручный боец"),
        ["FightingStyle_Dueling"] = ("Style: Dueling", "Стиль: Дуэлянт"),
        ["FightingStyle_GreatWeapon"] = ("Style: Great Weapon", "Стиль: Двуручное"),
        ["FightingStyle_TwoWeapons"] = ("Style: Two Weapons", "Стиль: Два оружия"),
        ["HasVersatileOneHanded"] = ("Versatile (1H)", "Универсальное (1 рука)"),
        ["HasVersatileTwoHanded"] = ("Versatile (2H)", "Универсальное (2 руки)"),
        ["HasWeapon"] = ("Has Weapon", "Есть оружие"),
        ["HasWeaponInMainHand"] = ("Weapon in Main Hand", "Оружие в основной"),
        ["IsOffHandSlotEmpty"] = ("Off Hand Empty", "Вторая рука пуста"),
        ["HasPactWeapon"] = ("Has Pact Weapon", "Оружие договора"),
        ["HasHexbladeWeapon"] = ("Hexblade Weapon", "Оружие Ведьмака"),
        ["HasCoatableWeapon"] = ("Coatable Weapon", "Можно покрыть оружие"),
        ["HasDippableWeapon"] = ("Dippable Weapon", "Можно обмакнуть оружие"),
        ["WieldingFinesseWeapon"] = ("Finesse Weapon", "Фехтовальное оружие"),
        ["WieldingFinesseWeaponInSpecificHand"] = ("Finesse in Hand", "Фехтовальное в руке"),
        ["HasHeavyArmor"] = ("Heavy Armor", "Тяжёлая броня"),
        ["HasMediumArmor"] = ("Medium Armor", "Средняя броня"),
        ["HasMetalArmor"] = ("Metal Armor", "Металлическая броня"),
        ["HasMetalWeapon"] = ("Metal Weapon", "Металлическое оружие"),
        ["HasMetalWeaponInAnyHand"] = ("Metal in Any Hand", "Металл в любой руке"),
        ["IsMetalCharacter"] = ("Metal Character", "Металлический персонаж"),
        ["IsMetalItem"] = ("Metal Item", "Металлический предмет"),
        ["CanDisarmWieldingWeapon"] = ("Can Disarm", "Можно обезоружить"),
        ["IsEquipmentSlot"] = ("Is Equipment Slot", "Слот экипировки"),
        ["IsInInventory"] = ("In Inventory", "В инвентаре"),
        ["HasEquipmentWithAttribute"] = ("Equipment with Attr", "Экипировка с атрибутом"),

        // ── Surface ───────────────────────────────────────────
        ["InSurface"] = ("In Surface", "На поверхности"),
        ["Surface"] = ("Surface At", "Поверхность в точке"),
        ["CanTransformSurface"] = ("Can Transform Surface", "Можно изменить поверхность"),
        ["IsDippableSurface"] = ("Dippable Surface", "Можно обмакнуть"),
        ["IsWaterBasedSurface"] = ("Water-Based Surface", "Водная поверхность"),
        ["IsInElectrifiedSurface"] = ("In Electrified Surface", "На электрической поверхности"),

        // ── Passive ───────────────────────────────────────────
        ["HasPassive"] = ("Has Passive", "Есть пассивка"),
        ["IsPassiveSource"] = ("Is Passive Source", "Источник пассивки"),
        ["IsPassiveOwner"] = ("Is Passive Owner", "Владелец пассивки"),
        ["AttackedWithPassiveSourceWeapon"] = ("Attacked w/ Passive Weapon", "Атака оружием пассивки"),

        // ── Resource ──────────────────────────────────────────
        ["HasActionResource"] = ("Has Resource", "Есть ресурс"),
        ["HasUseCosts"] = ("Has Use Costs", "Есть стоимость"),
        ["HasActionType"] = ("Has Action Type", "Тип действия"),
        ["HasAnySpells"] = ("Has Any Spells", "Есть заклинания"),
        ["SpellLevelEqualOrLessThan"] = ("Spell Lvl ≤", "Уровень закл. ≤"),
        ["SpellLevelEqualTo"] = ("Spell Lvl =", "Уровень закл. ="),
        ["SpellLevelEquals"] = ("Spell Lvl =", "Уровень закл. ="),
        ["SpellPowerLevelEqualOrLessThan"] = ("Power Lvl ≤", "Уровень силы ≤"),
        ["SpellPowerLevelEqualTo"] = ("Power Lvl =", "Уровень силы ="),

        // ── Tag ───────────────────────────────────────────────
        ["Tagged"] = ("Has Tag", "Есть тег"),
        ["HasAnyTags"] = ("Has Any Tags", "Есть любой тег"),
        ["HasNoTags"] = ("Has No Tags", "Нет тегов"),

        // ── Visibility / Obscurity ────────────────────────────
        ["CanSee"] = ("Can See", "Видит"),
        ["FacingMe"] = ("Facing Me", "Смотрит на меня"),
        ["IsInSightPyramid"] = ("In Sight", "В поле зрения"),
        ["IsInSunlight"] = ("In Sunlight", "На солнце"),
        ["HasObscuredState"] = ("Obscured State", "Степень скрытности"),
        ["HasObscuredStateAtPosition"] = ("Obscured at Pos", "Скрытность в точке"),
        ["CanSeeStatusSource"] = ("Can See Status Source", "Видит источник статуса"),
        ["HasLosToStatusSource"] = ("LoS to Status Source", "Видимость к статусу"),

        // ── Distance / Range ──────────────────────────────────
        ["Distance"] = ("Distance", "Расстояние"),
        ["DistanceToEntityHitBounds"] = ("Distance to Hit Bounds", "Расстояние до границ"),
        ["DistanceToGreaterThan"] = ("Distance >", "Расстояние >"),
        ["DistanceToTargetGreaterThan"] = ("To Target >", "До цели >"),
        ["DistanceToTargetGreaterOrEqual"] = ("To Target ≥", "До цели ≥"),
        ["DistanceToTargetLessThan"] = ("To Target <", "До цели <"),
        ["DistanceToEntityGreaterThan"] = ("To Entity >", "До объекта >"),
        ["DistanceToSource"] = ("To Source", "До источника"),
        ["DistanceToTarget"] = ("To Target", "До цели"),
        ["InMeleeRange"] = ("In Melee Range", "В зоне ближнего боя"),
        ["InReachWeaponRange"] = ("In Reach Range", "В зоне досягаемости"),
        ["IsWithinMeleeRangeExtended"] = ("In Extended Melee", "В расшир. зоне ближнего"),
        ["AreaRadiusGreaterThan"] = ("Area Radius >", "Радиус области >"),
        ["TargetRadiusGreaterThan"] = ("Target Radius >", "Радиус цели >"),
        ["YDistanceToTarget"] = ("Y Distance to Target", "Высота до цели"),
        ["YDistanceToTargetGreaterOrEqual"] = ("Y to Target ≥", "Высота до цели ≥"),

        // ── HP / Health ───────────────────────────────────────
        ["HasHPLessThan"] = ("HP <", "HP <"),
        ["HasHPMoreThan"] = ("HP >", "HP >"),
        ["HasHPPercentageLessThan"] = ("HP% <", "HP% <"),
        ["HasHPPercentageMoreThan"] = ("HP% >", "HP% >"),
        ["HasHPPercentageEqualOrLessThan"] = ("HP% ≤", "HP% ≤"),
        ["HasHPPercentageEqualOrMoreThan"] = ("HP% ≥", "HP% ≥"),
        ["HasHPPercentageWithoutTemporaryHPLessThan"] = ("Real HP% <", "Реал. HP% <"),
        ["HasHPPercentageWithoutTemporaryHPMoreThan"] = ("Real HP% >", "Реал. HP% >"),
        ["HasHPPercentageWithoutTemporaryHPEqualOrLessThan"] = ("Real HP% ≤", "Реал. HP% ≤"),
        ["HasHPPercentageWithoutTemporaryHPEqualOrMoreThan"] = ("Real HP% ≥", "Реал. HP% ≥"),
        ["HasMaxHP"] = ("Max HP", "Макс. HP"),
        ["HasMaxHPGreaterThan"] = ("Max HP >", "Макс. HP >"),
        ["HasMaxHPEqualOrGreaterThan"] = ("Max HP ≥", "Макс. HP ≥"),
        ["HasMaxHPLessThan"] = ("Max HP <", "Макс. HP <"),
        ["HasMaxHPEqualOrLessThan"] = ("Max HP ≤", "Макс. HP ≤"),
        ["HasMaxHPEqualTo"] = ("Max HP =", "Макс. HP ="),
        ["HasMaxHPBetween"] = ("Max HP Between", "Макс. HP между"),
        ["HasMaxHPWithoutTemporaryHP"] = ("Real Max HP", "Реал. макс. HP"),
        ["HasTemporaryHP"] = ("Has Temp HP", "Есть врем. HP"),
        ["MissingHPGreaterThan"] = ("Missing HP >", "Потеряно HP >"),
        ["HealDoneGreaterThan"] = ("Heal Done >", "Исцеление >"),
        ["CanRegainHP"] = ("Can Regain HP", "Может восстановить HP"),
        ["IsHealingOther"] = ("Healing Other", "Лечит другого"),
        ["IsHealingSupportSpell"] = ("Healing Spell", "Лечебное заклинание"),
        ["IsSelfHeal"] = ("Self Heal", "Самоисцеление"),
        ["IsSelfDamage"] = ("Self Damage", "Самоповреждение"),

        // ── Damage Type ───────────────────────────────────────
        ["HasDamageDoneForType"] = ("Damage of Type", "Урон типа"),
        ["HasDamageDoneForTypeIncludingZero"] = ("Damage of Type (incl. 0)", "Урон типа (вкл. 0)"),
        ["HasAttackDamageDoneForType"] = ("Attack Dmg of Type", "Атака урон типа"),
        ["TotalDamageDoneGreaterThan"] = ("Total Damage >", "Общий урон >"),
        ["TotalAttackDamageDoneGreaterThan"] = ("Total Atk Dmg >", "Общий урон атаки >"),
        ["MainDamageTypeIs"] = ("Main Damage Type", "Основной тип урона"),
        ["IsPhysicalDamage"] = ("Physical Damage", "Физический урон"),
        ["IsEnergyDamage"] = ("Energy Damage", "Энергетический урон"),
        ["IsFallDamage"] = ("Fall Damage", "Урон от падения"),
        ["IsRedirectedDamage"] = ("Redirected Damage", "Перенаправленный урон"),
        ["IsHitpointsDamaged"] = ("HP Damaged", "HP повреждён"),
        ["IsDamagedByOther"] = ("Damaged By Other", "Получил урон от другого"),
        ["IsDamageTypeSlashing"] = ("Slashing", "Рубящий"),
        ["IsDamageTypePiercing"] = ("Piercing", "Колющий"),
        ["IsDamageTypeBludgeoning"] = ("Bludgeoning", "Дробящий"),
        ["IsDamageTypeFire"] = ("Fire", "Огонь"),
        ["IsDamageTypeCold"] = ("Cold", "Холод"),
        ["IsDamageTypeLightning"] = ("Lightning", "Молния"),
        ["IsDamageTypeThunder"] = ("Thunder", "Гром"),
        ["IsDamageTypePoison"] = ("Poison", "Яд"),
        ["IsDamageTypeAcid"] = ("Acid", "Кислота"),
        ["IsDamageTypeNecrotic"] = ("Necrotic", "Некротический"),
        ["IsDamageTypeRadiant"] = ("Radiant", "Сияние"),
        ["IsDamageTypePsychic"] = ("Psychic", "Психический"),
        ["IsDamageTypeForce"] = ("Force", "Силовой"),
        ["HasDamageEffectFlag"] = ("Damage Effect Flag", "Флаг эффекта урона"),
        ["HasDeathType"] = ("Death Type", "Тип смерти"),
        ["FrozenStatusRemovalDamage"] = ("Frozen Removal Dmg", "Урон снятия заморозки"),

        // ── Ability / Skill ───────────────────────────────────
        ["HasAttribute"] = ("Has Attribute", "Есть атрибут"),
        ["IsAbilityChecked"] = ("Ability Checked", "Проверка характеристики"),
        ["IsSkillChecked"] = ("Skill Checked", "Проверка навыка"),
        ["AttackRollAbility"] = ("Attack Roll Ability", "Характеристика броска"),
        ["WeaponAttackRollAbility"] = ("Weapon Roll Ability", "Характеристика оружия"),
        ["CharacterLevelGreaterThan"] = ("Char Level >", "Уровень персонажа >"),
        ["ClassLevelHigherOrEqualThan"] = ("Class Level ≥", "Уровень класса ≥"),
        ["AbilityGreaterThan"] = ("Ability >", "Характеристика >"),
        ["CharismaGreaterThan"] = ("Charisma >", "Харизма >"),
        ["AMP_CharismaGreaterThan"] = ("AMP: Charisma >", "AMP: Харизма >"),
        ["IntelligenceGreaterThan"] = ("Intelligence >", "Интеллект >"),
        ["IsDexterityGreaterThanStrength"] = ("Dex > Str", "Лов > Сил"),
        ["IsWisdomGreaterThanStrength"] = ("Wis > Str", "Мдр > Сил"),
        ["IsCharismaModifierPositive"] = ("Cha Mod > 0", "Модификатор Хар > 0"),
        ["CharismaModifierEqualsOrLessThan"] = ("Cha Mod ≤", "Мод. Хар ≤"),
        ["CharismaModifierEqualsTo"] = ("Cha Mod =", "Мод. Хар ="),
        ["CheckedPhysicalAbility"] = ("Checked Phys Ability", "Проверка физической"),
        ["HasZeroConstitution"] = ("Zero Con", "Выносливость = 0"),
        ["HasExactlyZeroConstitution"] = ("Exactly Zero Con", "Точно Вын = 0"),
        ["SavingThrowWithHigherAbility"] = ("Save w/ Higher Ability", "Спасбросок лучшей хар."),
        ["GetPreferredCastingAbility"] = ("Preferred Cast Ability", "Предпочтит. кастовая"),

        // ── Race / Type ───────────────────────────────────────
        ["Race"] = ("Race Is", "Раса"),
        ["IsUndead"] = ("Is Undead", "Нежить"),
        ["IsConstruct"] = ("Is Construct", "Конструкт"),
        ["IsUndeadOrConstruct"] = ("Undead/Construct", "Нежить/конструкт"),
        ["UndeadOrFiend"] = ("Undead/Fiend", "Нежить/исчадие"),
        ["IsSummon"] = ("Is Summon", "Призванное"),
        ["IsSummonWithoutMouth"] = ("Summon w/o Mouth", "Призыв без рта"),
        ["IsNotHumanoid"] = ("Not Humanoid", "Не гуманоид"),
        ["PlayableRace"] = ("Playable Race", "Играбельная раса"),
        ["IsKarlach"] = ("Is Karlach", "Это Карлах"),

        // ── Size ──────────────────────────────────────────────
        ["SizeEqualOrSmaller"] = ("Size ≤", "Размер ≤"),
        ["SizeEqualOrGreater"] = ("Size ≥", "Размер ≥"),
        ["SizeGreater"] = ("Size >", "Размер >"),
        ["TargetSizeEqualOrSmaller"] = ("Target Size ≤", "Размер цели ≤"),

        // ── Resistance / Immunity ─────────────────────────────
        ["IsImmuneToPoisonDamage"] = ("Immune to Poison", "Иммунитет к яду"),
        ["IsResistantToPoisonDamage"] = ("Resistant to Poison", "Сопротивление яду"),
        ["IsImmuneToColdDamage"] = ("Immune to Cold", "Иммунитет к холоду"),
        ["IsResistantToColdDamage"] = ("Resistant to Cold", "Сопротивление холоду"),
        ["IsImmuneToDamageType"] = ("Immune to Dmg Type", "Иммунитет к типу урона"),
        ["IsResistantToDamageType"] = ("Resistant to Dmg Type", "Сопротивление типу урона"),
        ["IsImmuneToForceDamage"] = ("Immune to Force", "Иммунитет к силовому"),
        ["IsResistantToForceDamage"] = ("Resistant to Force", "Сопротивление силовому"),
        ["IsResistantToNecroticDamage"] = ("Resistant to Necrotic", "Сопротивление некротическому"),
        ["IsResistantToFireAndCold"] = ("Resist Fire+Cold", "Сопротивление огню и холоду"),
        ["IsResistantToFireOrCold"] = ("Resist Fire/Cold", "Сопротивление огню или холоду"),
        ["HasEvasion"] = ("Has Evasion", "Уклонение"),

        // ── Metamagic / Class features ────────────────────────
        ["CarefulSpellCheck"] = ("Careful Spell", "Осторожное заклинание"),
        ["QuickenedSpellCheck"] = ("Quickened Spell", "Ускоренное заклинание"),
        ["QuickenedCantripCheck"] = ("Quickened Cantrip", "Ускоренный заговор"),
        ["SubtleSpellCheck"] = ("Subtle Spell", "Незаметное заклинание"),
        ["EmpoweredSpellCheck"] = ("Empowered Spell", "Усиленное заклинание"),
        ["ExtendedSpellCheck"] = ("Extended Spell", "Продлённое заклинание"),
        ["DistantSpellCheck"] = ("Distant Spell", "Далёкое заклинание"),
        ["DistantTouchSpellCheck"] = ("Distant Touch Spell", "Далёкое касание"),
        ["HeightenedSpellCheck"] = ("Heightened Spell", "Повышенное заклинание"),
        ["HeightenedNecromancySpellCheck"] = ("Heightened Necromancy", "Повышенная некромантия"),
        ["TwinnedTargetSpellCheck"] = ("Twinned Target", "Удвоение (цель)"),
        ["TwinnedProjectileSpellCheck"] = ("Twinned Projectile", "Удвоение (снаряд)"),
        ["TwinnedCantripTargetSpellCheck"] = ("Twinned Cantrip Target", "Удвоение заговора (цель)"),
        ["TwinnedCantripProjectileSpellCheck"] = ("Twinned Cantrip Proj", "Удвоение заговора (снаряд)"),
        ["TwinnedTargetTouchSpellCheck"] = ("Twinned Touch", "Удвоение (касание)"),
        ["CounterspellCheck"] = ("Counterspell", "Контрзаклинание"),
        ["MindSanctuaryCheck"] = ("Mind Sanctuary", "Убежище разума"),
        ["FreecastCheck"] = ("Freecast", "Свободный каст"),
        ["FreeCastSpellLevel1"] = ("Freecast Lvl 1", "Свободный 1 ур."),
        ["FreeCastSpellLevel3OrLower"] = ("Freecast Lvl ≤3", "Свободный ≤3 ур."),
        ["BardSpellCheck"] = ("Bard Spell", "Заклинание барда"),
        ["ExtraAttackCheck"] = ("Extra Attack", "Доп. атака"),
        ["ExtraAttackSpellCheck"] = ("Extra Attack Spell", "Доп. атака (закл.)"),
        ["HasAnyExtraAttack"] = ("Has Extra Attack", "Есть доп. атака"),
        ["HasAnyExtraAttackQueued"] = ("Extra Attack Queued", "Доп. атака в очереди"),
        ["HasExtraAttackPassive"] = ("Extra Attack Passive", "Пассивка доп. атаки"),
        ["ManeuverAndWeaponActionCheck"] = ("Maneuver Check", "Проверка манёвра"),
        ["ManeuverSaveDC"] = ("Maneuver Save DC", "КС спасброска манёвра"),
        ["GreatWeaponMaster"] = ("Great Weapon Master", "Мастер двуручного"),
        ["Sharpshooter"] = ("Sharpshooter", "Снайпер"),
        ["BladesongAvaliable"] = ("Bladesong Available", "Песнь клинка доступна"),
        ["BladesongAttackCheck"] = ("Bladesong Attack", "Атака песни клинка"),
        ["IsRage"] = ("Is Rage", "В ярости"),
        ["WildMagicSpell"] = ("Wild Magic Spell", "Дикая магия"),
        ["IsAquamancerPower"] = ("Aquamancer Power", "Сила аквамансера"),
        ["IsTadpolePower"] = ("Tadpole Power", "Сила головастика"),
        ["HasTadpolePower"] = ("Has Tadpole Power", "Есть сила головастика"),
        ["GetTadpolePowersNumber"] = ("Tadpole Powers Count", "Кол-во сил головастика"),
        ["HasLessHPThanTadpolePowers"] = ("HP < Tadpole Powers", "HP < сил головастика"),
        ["IsBurningAgony"] = ("Burning Agony", "Пылающая агония"),
        ["IsWarWizardSpellTier1"] = ("War Wizard Tier 1", "Боевой маг ур. 1"),
        ["IsWarWizardSpellTier2"] = ("War Wizard Tier 2", "Боевой маг ур. 2"),
        ["IsWarWizardSpellTier3"] = ("War Wizard Tier 3", "Боевой маг ур. 3"),
        ["ElementalAffinityCheck"] = ("Elemental Affinity", "Стихийное сродство"),
        ["DampenElementsCheck"] = ("Dampen Elements", "Подавление стихий"),
        ["ArcaneTricksterQuickenedSpellFilter"] = ("Arcane Trickster Quick", "Ускорение трикстера"),
        ["IsImprovedPactOfTheChain"] = ("Improved Pact Chain", "Улучш. Пакт Цепи"),
        ["WarlockSlotNotFull"] = ("Warlock Slot Not Full", "Слот варлока не полон"),
        ["SpellSavantAmuletAdditionalSpellCheck"] = ("Spell Savant Amulet", "Амулет знатока"),
        ["CanUseSpellScroll"] = ("Can Use Scroll", "Может читать свиток"),
        ["AreSpellScrollsClassRestricted"] = ("Scrolls Class Restricted", "Свитки по классу"),
        ["CanUseWeaponActions"] = ("Can Use Weapon Actions", "Может исп. действия оружия"),

        // ── Advantage conditions ──────────────────────────────
        ["AdvantageOnCharmed"] = ("Adv. vs Charmed", "Преим. против очарования"),
        ["AdvantageOnFrightened"] = ("Adv. vs Frightened", "Преим. против испуга"),
        ["AdvantageOnParalyzed"] = ("Adv. vs Paralyzed", "Преим. против паралича"),
        ["AdvantageOnPoisoned"] = ("Adv. vs Poisoned", "Преим. против яда"),
        ["AdvantageOnRestrained"] = ("Adv. vs Restrained", "Преим. против захвата"),
        ["AdvantageOnSlipping"] = ("Adv. vs Slipping", "Преим. против скольжения"),
        ["AdvantageOnTurned"] = ("Adv. vs Turned", "Преим. против изгнания"),
        ["AdvantageOnCharmPerson"] = ("Adv. vs Charm Person", "Преим. против очар. лиц"),
        ["AdvantageOnOrinFear"] = ("Adv. vs Orin Fear", "Преим. против страха Орин"),
        ["DisadvantageOnFrightened"] = ("Disadv. vs Frightened", "Помеха против испуга"),
        ["DisadvantageOnRestrained"] = ("Disadv. vs Restrained", "Помеха против захвата"),
        ["InterruptHasAdvantage"] = ("Interrupt Has Adv", "Реакция с преим."),
        ["InterruptHasDisadvantage"] = ("Interrupt Has Disadv", "Реакция с помехой"),

        // ── Throw / Shove ─────────────────────────────────────
        ["CanThrowWeight"] = ("Can Throw Weight", "Может бросить вес"),
        ["CanShoveWeight"] = ("Can Shove Weight", "Может толкнуть вес"),
        ["CanPickUpWeight"] = ("Can Pick Up Weight", "Может поднять вес"),
        ["CanBarbarianGiantShoveWeight"] = ("Barbarian Giant Shove", "Толчок великана"),
        ["CanImprovisedWeaponWeight"] = ("Improvised Weapon Wt", "Вес импровиз. оружия"),
        ["HasWeightGreaterThan"] = ("Weight >", "Вес >"),
        ["HasLiftingWeightGreaterThan"] = ("Lifting Weight >", "Грузоподъёмность >"),
        ["ThrowableCheck"] = ("Throwable", "Можно бросить"),
        ["ThrowOrFirstAttack"] = ("Throw/First Attack", "Бросок/первая атака"),
        ["IsEntityThrownObject"] = ("Thrown Object", "Брошенный предмет"),
        ["IsHeavyThrownObject"] = ("Heavy Thrown", "Тяжёлый бросок"),
        ["IsLightThrownObject"] = ("Light Thrown", "Лёгкий бросок"),
        ["IsMediumThrownObject"] = ("Medium Thrown", "Средний бросок"),
        ["HasThrownWeaponInInventory"] = ("Thrown Weapon in Inv", "Метательное в инвентаре"),
        ["ShoveCheck"] = ("Shove Check", "Проверка толчка"),
        ["IsTargetableCorpse"] = ("Targetable Corpse", "Целевой труп"),

        // ── Status duration ───────────────────────────────────
        ["StatusDurationLessThan"] = ("Status Duration <", "Длит. статуса <"),
        ["StatusDurationMoreThan"] = ("Status Duration >", "Длит. статуса >"),
        ["StatusDurationEqualOrLessThan"] = ("Status Duration ≤", "Длит. статуса ≤"),
        ["StatusDurationEqualOrMoreThan"] = ("Status Duration ≥", "Длит. статуса ≥"),
        ["StatusGroupDurationLessThan"] = ("Group Duration <", "Длит. группы <"),
        ["StatusGroupDurationMoreThan"] = ("Group Duration >", "Длит. группы >"),
        ["StatusGroupDurationEqual"] = ("Group Duration =", "Длит. группы ="),
        ["StatusGroupDurationEqualOrLessThan"] = ("Group Duration ≤", "Длит. группы ≤"),
        ["StatusGroupDurationEqualOrMoreThan"] = ("Group Duration ≥", "Длит. группы ≥"),
        ["HasDuration"] = ("Has Duration", "Есть длительность"),
        ["GetStatusDuration"] = ("Get Status Duration", "Получить длит. статуса"),
        ["MaximumLowStackableStatus"] = ("Max Low Stackable", "Макс. низкий стак"),
        ["MaximumHighStackableStatus"] = ("Max High Stackable", "Макс. высокий стак"),
        ["MaximumHigherStackableStatus"] = ("Max Higher Stackable", "Макс. высший стак"),
        ["AppliesCrowdControlStatus"] = ("Applies CC Status", "Накладывает CC"),

        // ── Misc gameplay ─────────────────────────────────────
        ["CanHarm"] = ("Can Harm", "Может навредить"),
        ["CanPickup"] = ("Can Pick Up", "Может подобрать"),
        ["CanStand"] = ("Can Stand", "Может стоять"),
        ["CanShortRest"] = ("Can Short Rest", "Может кор. отдых"),
        ["CanAttack"] = ("Can Attack", "Может атаковать"),
        ["IsAbleToReact"] = ("Can React", "Может реагировать"),
        ["RemoveCause"] = ("Remove Cause", "Причина снятия"),
        ["HasContextFlag"] = ("Has Context Flag", "Флаг контекста"),
        ["HasFunctor"] = ("Has Functor", "Есть функтор"),
        ["CheckRulesetModifier"] = ("Ruleset Modifier", "Модификатор правил"),
        ["IsStoryItem"] = ("Story Item", "Сюжетный предмет"),
        ["IsSupply"] = ("Is Supply", "Припас"),
        ["IsItemDisabled"] = ("Item Disabled", "Предмет отключён"),
        ["IsAttackingOther"] = ("Attacking Other", "Атакует другого"),
        ["NumberOfTargetsGreaterThan"] = ("Num Targets >", "Кол-во целей >"),
        ["HasAllyWithinRange"] = ("Ally in Range", "Союзник в радиусе"),
        ["HasEnemyWithinRange"] = ("Enemy in Range", "Враг в радиусе"),
        ["GetAlliesWithinRange"] = ("Allies in Range", "Союзники в радиусе"),
        ["GetEnemiesWithinRange"] = ("Enemies in Range", "Враги в радиусе"),
        ["HasVerbalComponentBlocked"] = ("Verbal Blocked", "Словесный компонент заблок."),
        ["HasSpellCastBlocked"] = ("Spellcast Blocked", "Каст заблокирован"),
        ["AnyEntityIsItem"] = ("Any Entity Is Item", "Любой объект — предмет"),
        ["IsObserverAttacker"] = ("Observer Is Attacker", "Наблюдатель — атакующий"),
        ["IsObserverTargeted"] = ("Observer Is Target", "Наблюдатель — цель"),
        ["IsObserverVictim"] = ("Observer Is Victim", "Наблюдатель — жертва"),
        ["IsInflicterEqualToSource"] = ("Inflicter = Source", "Наносящий = Источник"),
        ["StatusDoesNotInterruptPerform"] = ("No Interrupt Perform", "Не прерывает выступление"),
        ["StatusDoesNotInvokeOnStatusApply"] = ("No OnStatusApply", "Не вызывает OnStatusApply"),
        ["Uninterruptible"] = ("Uninterruptible", "Непрерываемый"),
        ["HasInterruptedAttack"] = ("Interrupted Attack", "Прерванная атака"),
        ["HasInterruptedSavingThrow"] = ("Interrupted Save", "Прерванный спасбросок"),
        ["HasLastAttackTriggered"] = ("Last Attack Triggered", "Послед. атака сработала"),
        ["IsLastConditionRollSuccess"] = ("Last Condition Success", "Послед. условие успех"),
        ["IsLastSavingThrowRollSuccess"] = ("Last Save Success", "Послед. спасбросок успех"),
        ["IsPacifistDamageSpell"] = ("Pacifist Damage", "Пацифист урон"),
        ["IsPacifistHealingSpell"] = ("Pacifist Healing", "Пацифист лечение"),
        ["SpellAutoResolveOnAlly"] = ("Auto Resolve Ally", "Авторезолв на союзника"),
        ["SpellAutoResolveOnCharmed"] = ("Auto Resolve Charmed", "Авторезолв на очарованного"),
        ["SpellAutoResolveOnSelf"] = ("Auto Resolve Self", "Авторезолв на себя"),
        ["SpellDoesntApplyToElvesOrUndead"] = ("Not Elves/Undead", "Не работает на эльфов/нежить"),
        ["HasMarkingStatusCondition"] = ("Has Marking Status", "Есть метящий статус"),
        ["HasWarriorCombatDebuff"] = ("Warrior Combat Debuff", "Дебафф воина в бою"),
        ["GreaterInvisibilityCheck_InvisSpellOrRoll"] = ("Greater Invisibility", "Великая невидимость"),
        ["GreaterNecromancySpellFilter"] = ("Greater Necromancy", "Великая некромантия"),
        ["AutoStabilizeCondition"] = ("Auto Stabilize", "Авто-стабилизация"),
        ["FearStatusSavingCheck"] = ("Fear Saving Check", "Спасбросок от страха"),

        // ── Special / BG3-specific ────────────────────────────
        ["HasAuraOfVitality"] = ("Aura of Vitality", "Аура жизненной силы"),
        ["HasBladesongClimaxBlocked"] = ("Bladesong Climax Blocked", "Песнь клинка заблок."),
        ["BlinkCheck"] = ("Blink Check", "Мерцание"),
        ["BlackTentaclesCheck"] = ("Black Tentacles", "Чёрные щупальца"),
        ["WallOfFireCheck"] = ("Wall of Fire", "Стена огня"),
        ["ResilientSphereCheck"] = ("Resilient Sphere", "Сфера непробиваемости"),
        ["TelekinesisCheck"] = ("Telekinesis", "Телекинез"),
        ["MageHandCheck"] = ("Mage Hand", "Рука мага"),
        ["HeatMetalInitialCheck"] = ("Heat Metal Initial", "Раскалённый металл (начало)"),
        ["HeatMetalReapplyCheck"] = ("Heat Metal Reapply", "Раскалённый металл (повтор)"),
        ["ShadowCurseUndead"] = ("Shadow Curse Undead", "Проклятие тени (нежить)"),
        ["AspectOfChimpanzeeSavingCheck"] = ("Aspect Chimpanzee Save", "Аспект шимпанзе спас."),
        ["GithyankiPheromonesCheck"] = ("Githyanki Pheromones", "Феромоны гитьянки"),
        ["FrostCounterRequirement"] = ("Frost Counter Req", "Счётчик мороза"),
        ["FrostHatRequirement"] = ("Frost Hat Req", "Морозная шляпа"),
        ["ForceConduitBlastRequirement"] = ("Force Conduit Blast", "Силовой взрыв"),
        ["MentalFatigueDischargeRequirement"] = ("Mental Fatigue Req", "Умственная усталость"),
        ["RadiatingOrbBlindDuration"] = ("Radiating Orb Blind", "Сияющая сфера: слепота"),
        ["ReverberationBlastRequirement"] = ("Reverberation Blast", "Реверберация"),
        ["ChargedLightningAuraRequirement"] = ("Lightning Aura Req", "Молниевая аура"),
        ["HasMaximumLightningCharge"] = ("Max Lightning Charge", "Макс. заряд молнии"),
        ["IsDischargingLightning"] = ("Discharging Lightning", "Разряд молнии"),
        ["OmenRolling"] = ("Omen Rolling", "Бросок предзнаменования"),
        ["LuckOfTheFarRealmCheck"] = ("Luck Far Realm", "Удача Дальнего мира"),
        ["BecomeHagControlled"] = ("Hag Controlled", "Под контролем Карги"),
        ["BecomePaladinHagControlled"] = ("Paladin Hag Controlled", "Паладин под Каргой"),
        ["IsSlayerForm"] = ("Slayer Form", "Форма убийцы"),
        ["HasFleshToSToneCheck"] = ("Flesh to Stone", "Плоть в камень"),
        ["MobileShootingCasterCondition"] = ("Mobile Shooting", "Мобильная стрельба"),
        ["IsCurvingShot"] = ("Curving Shot", "Искривлённый выстрел"),
        ["IsCurvingShotMiss"] = ("Curving Shot Miss", "Промах искр. выстрела"),
        ["HasNotPrecisionAttack"] = ("No Precision Attack", "Нет точной атаки"),
        ["RushWeaponActionTargetCondition"] = ("Rush Target", "Цель рывка"),
        ["NetRemovalCondition"] = ("Net Removal", "Снятие сети"),
        ["InitialHideCheck"] = ("Initial Hide", "Начальная скрытность"),
        ["PirateGrenadeAvailable"] = ("Pirate Grenade Ready", "Пиратская граната готова"),
        ["NextPirateGrenadeSlot"] = ("Next Pirate Grenade", "Следующая граната"),
        ["HasOrphicHammer"] = ("Has Orphic Hammer", "Есть Орфический молот"),
        ["JumpSpell"] = ("Jump Spell", "Заклинание прыжка"),
        ["SpellSniperCheck"] = ("Spell Sniper", "Снайпер заклинаний"),
        ["MagicItemPoweredSpellCheck"] = ("Magic Item Spell", "Закл. магического предмета"),
        ["MagicMissileSpellCheck"] = ("Magic Missile", "Волшебная стрела"),
        ["MagicalAmbushCheck"] = ("Magical Ambush", "Магическая засада"),
        ["WyvernPoison"] = ("Wyvern Poison", "Яд виверны"),
        ["TutorialSummonBlockCheck"] = ("Tutorial Summon Block", "Блок призыва (туториал)"),
        ["IsRecastSpell"] = ("Recast Spell", "Повторный каст"),
        ["IsTrap"] = ("Is Trap", "Ловушка"),
        ["IsPsychicDominance"] = ("Psychic Dominance", "Психическое доминирование"),
        ["HasActiveAstralKnowledge"] = ("Astral Knowledge", "Астральное знание"),
        ["HasAnyHaste"] = ("Has Haste", "Ускорен"),
        ["IsSlow"] = ("Is Slow", "Замедлен"),

        // ── Wild Shape / Forms ────────────────────────────────
        ["IsEarthMyrmidonWildShape"] = ("Earth Myrmidon Form", "Форма земляного мирмидона"),
        ["UndeadThrallAnimateDeadSpellVariation"] = ("Undead Thrall Animate", "Анимация мёртвых (раб)"),
        ["SlayerFormExtraAttackSpellCheck"] = ("Slayer Extra Attack", "Доп. атака убийцы"),

        // ── Spell filters (metamagic/split etc.) ──────────────
        ["SplitEnchantmentProjectileSpellCheck"] = ("Split Enchant Proj", "Расщепление (снаряд)"),
        ["SplitEnchantmentTargetSpellCheck"] = ("Split Enchant Target", "Расщепление (цель)"),
        ["SplitEnchantmentTargetTouchSpellCheck"] = ("Split Enchant Touch", "Расщепление (касание)"),
        ["TwinnedTargetSpellCheckReaper"] = ("Twinned Reaper Target", "Удвоение жнеца (цель)"),
        ["TwinnedProjectileSpellCheckReaper"] = ("Twinned Reaper Proj", "Удвоение жнеца (снаряд)"),
        ["TwinnedTargetTouchSpellCheckReaper"] = ("Twinned Reaper Touch", "Удвоение жнеца (касание)"),
        ["TwinnedCantripTargetTouchSpellCheck"] = ("Twinned Cantrip Touch", "Удвоение заговора (касание)"),
        ["NonSpellMetamagicAbilities"] = ("Non-Spell Metamagic", "Метамагия (не закл.)"),
        ["MetamagicExclusionSpells"] = ("Metamagic Exclusion", "Исключение метамагии"),
        ["HeatConvergenceFireSpellCheck"] = ("Heat Convergence Fire", "Конвергенция жара"),
        ["FireProjectileSpellCheck"] = ("Fire Projectile Spell", "Закл. огн. снаряда"),
        ["FireProjectileSpellCheckWithCantrips"] = ("Fire Proj + Cantrips", "Огн. снаряд + заговоры"),
        ["SpellSchoolFilter"] = ("Spell School Filter", "Фильтр школы"),
        ["RangedSpellAttackCheck"] = ("Ranged Spell Atk Check", "Дальняя магическая атака"),
        ["SpellAttackCheck"] = ("Spell Attack Check", "Проверка магической атаки"),
        ["MeleeUnarmedAttackCheck"] = ("Melee Unarmed Check", "Ближняя безоружная проверка"),
        ["Level2HitCostSpellCheck"] = ("Level 2 Hit Cost", "Стоимость попадания 2 ур."),

        // ── Feat requirements ─────────────────────────────────
        ["FeatRequirementAbilityGreaterEqual"] = ("Feat: Ability ≥", "Черта: Хар ≥"),
        ["FeatRequirementHasAnySpell"] = ("Feat: Has Spells", "Черта: Есть заклинания"),
        ["FeatRequirementProficiency"] = ("Feat: Proficiency", "Черта: Владение"),

        // ── Misc internal / rarely used ───────────────────────
        ["GetModifier"] = ("Get Modifier", "Получить модификатор"),
        ["GetAttackAdvantage"] = ("Get Attack Advantage", "Получить преим. атаки"),
        ["GetActiveArmor"] = ("Get Active Armor", "Получить активную броню"),
        ["GetEquipmentSlot"] = ("Get Equip Slot", "Получить слот экип."),
        ["GetItemInEquipmentSlot"] = ("Get Item in Slot", "Предмет в слоте"),
        ["GetAttackWeapon"] = ("Get Attack Weapon", "Оружие атаки"),
        ["GetActiveWeapon"] = ("Get Active Weapon", "Активное оружие"),
        ["GetSpellTargetRadius"] = ("Spell Target Radius", "Радиус цели заклинания"),
        ["GetSpellAreaRadius"] = ("Spell Area Radius", "Радиус области заклинания"),
        ["GetSummoner"] = ("Get Summoner", "Получить призывателя"),
        ["GetOwner"] = ("Get Owner", "Получить владельца"),
        ["CalculateSpellDC"] = ("Calculate Spell DC", "Рассчитать КС заклинания"),
        ["CalculateManeuverSaveDC"] = ("Maneuver Save DC", "КС манёвра"),
        ["GenericSaveDC"] = ("Generic Save DC", "Общий КС спасброска"),
        ["SourceSpellDC"] = ("Source Spell DC", "КС источника"),
        ["HybridCasterWeaponActionDC"] = ("Hybrid Caster DC", "КС гибридного кастера"),
        ["GetItemsInInventory"] = ("Items in Inventory", "Предметы в инвентаре"),
        ["GetLiftingWeight"] = ("Get Lifting Weight", "Грузоподъёмность"),
        ["Roll"] = ("Roll Dice", "Бросок кубиков"),
        ["Attack"] = ("Attack Roll", "Бросок атаки"),
        ["CanSee"] = ("Can See", "Может видеть"),
        ["HasSpellRangeEqualOrLessThan"] = ("Spell Range ≤", "Дальность закл. ≤"),
        ["IsWizard"] = ("Is Wizard", "Волшебник"),
        ["IsWizardIceStorm"] = ("Wizard Ice Storm", "Ледяная буря волшебника"),
        ["IsClericCantrip"] = ("Cleric Cantrip", "Заговор жреца"),
        ["IsBardicInspirationSpell"] = ("Bardic Inspiration", "Бардовское вдохновение"),
        ["IsShadowStepSpell"] = ("Shadow Step", "Шаг сквозь тень"),
        ["IsMonkWeaponAttack"] = ("Monk Weapon Attack", "Атака оружием монаха"),
        ["IsSmiteSpells"] = ("Smite Spell", "Кара (заклинание)"),
        ["IsSmiteStatusCondition"] = ("Smite Status", "Статус кары"),
        ["IsExtraAttackStatuses"] = ("Extra Attack Statuses", "Статусы доп. атаки"),
        ["HasHigherPriorityExtraAttackQueued"] = ("Higher Priority Extra Atk", "Приоритетная доп. атака"),
        ["IsFlatValueInterruptInteresting"] = ("Flat Value Interrupt", "Плоское значение (реакция)"),
        ["IsPortentInterruptInteresting"] = ("Portent Interrupt", "Предсказание (реакция)"),
        ["IsSetInterruptInteresting"] = ("Set Interrupt", "Установка (реакция)"),
        ["IsRerollInterruptInteresting"] = ("Reroll Interrupt", "Переброс (реакция)"),
        ["HasSavingThrowWithAbility"] = ("Save w/ Ability", "Спасбросок характеристикой"),
        ["IsAttackType"] = ("Attack Type Is", "Тип атаки"),
        ["ArcaneAcuityGlovesCondition"] = ("Arcane Acuity Gloves", "Перчатки магической точности"),
        ["ArcaneWardOverflow"] = ("Arcane Ward Overflow", "Переполнение магического щита"),
    };

    // ═══════════════════════════════════════════════════════════
    // SURFACE LABELS — (English, Russian)
    // Keys match ConditionSchema.InSurfaceValues
    // ═══════════════════════════════════════════════════════════

    public static readonly Dictionary<string, (string En, string Ru)> Surfaces = new(StringComparer.OrdinalIgnoreCase)
    {
        ["SurfaceNone"] = ("None", "Нет"),
        ["SurfaceWater"] = ("Water", "Вода"),
        ["SurfaceWaterElectrified"] = ("Electrified Water", "Электрическая вода"),
        ["SurfaceWaterFrozen"] = ("Frozen Water", "Замёрзшая вода"),
        ["SurfaceBlood"] = ("Blood", "Кровь"),
        ["SurfaceBloodElectrified"] = ("Electrified Blood", "Электрическая кровь"),
        ["SurfaceBloodFrozen"] = ("Frozen Blood", "Замёрзшая кровь"),
        ["SurfacePoison"] = ("Poison", "Яд"),
        ["SurfaceOil"] = ("Oil", "Масло"),
        ["SurfaceLava"] = ("Lava", "Лава"),
        ["SurfaceGrease"] = ("Grease", "Жир"),
        ["SurfaceWeb"] = ("Web", "Паутина"),
        ["SurfaceDeepwater"] = ("Deep Water", "Глубокая вода"),
        ["SurfaceFire"] = ("Fire", "Огонь"),
        ["SurfaceAcid"] = ("Acid", "Кислота"),
        ["SurfaceMud"] = ("Mud", "Грязь"),
        ["SurfaceAlcohol"] = ("Alcohol", "Алкоголь"),
        ["SurfaceHellfire"] = ("Hellfire", "Адское пламя"),
        ["SurfaceAsh"] = ("Ash", "Пепел"),
        ["SurfaceSpikeGrowth"] = ("Spike Growth", "Шипастый рост"),
        ["SurfaceHolyFire"] = ("Holy Fire", "Священный огонь"),
        ["SurfaceBlackTentacles"] = ("Black Tentacles", "Чёрные щупальца"),
        ["SurfaceOvergrowth"] = ("Overgrowth", "Разрастание"),
        ["SurfaceWaterCloud"] = ("Water Cloud", "Водяное облако"),
        ["SurfaceWaterCloudElectrified"] = ("Electrified Cloud", "Электрическое облако"),
        ["SurfacePoisonCloud"] = ("Poison Cloud", "Ядовитое облако"),
        ["SurfaceCloudkillCloud"] = ("Cloudkill", "Облако смерти"),
        ["SurfaceDarknessCloud"] = ("Darkness Cloud", "Облако тьмы"),
        ["SurfaceFogCloud"] = ("Fog Cloud", "Туман"),
        ["SurfaceIceCloud"] = ("Ice Cloud", "Ледяное облако"),
        ["SurfaceSentinel"] = ("Sentinel", "Страж"),
        ["SurfaceBladeBarrier"] = ("Blade Barrier", "Стена клинков"),
        ["SurfaceCausticBrine"] = ("Caustic Brine", "Едкий рассол"),
        ["SurfaceWaterDeepRunning"] = ("Deep Running Water", "Глубокая течение"),
        ["SurfaceWaterRunning"] = ("Running Water", "Текущая вода"),
        ["SurfaceSurfaceDeepWater"] = ("Surface Deep Water", "Глубокая вода (пов.)"),
        ["SurfaceSurfaceDeepWaterRunning"] = ("Deep Water Running", "Глубокая текущая вода"),
        ["SurfaceSurfaceWaterElectrified"] = ("Surface Water Electrified", "Электр. вода (пов.)"),
        ["SurfaceVines"] = ("Vines", "Лозы"),
    };

    // ═══════════════════════════════════════════════════════════
    // CATEGORY LABELS — (English, Russian)
    // Used for grouping conditions in "Add Condition" menu
    // ═══════════════════════════════════════════════════════════

    public static readonly Dictionary<string, (string En, string Ru)> Categories = new()
    {
        ["Target"] = ("Target", "Цель"),
        ["Combat"] = ("Combat", "Бой"),
        ["State"] = ("State", "Состояние"),
        ["Status"] = ("Status", "Статусы"),
        ["Attack"] = ("Attack", "Атака"),
        ["Roll"] = ("Roll", "Броски"),
        ["Spell"] = ("Spell", "Заклинания"),
        ["Equipment"] = ("Equipment", "Экипировка"),
        ["Surface"] = ("Surface", "Поверхности"),
        ["Passive"] = ("Passive", "Пассивки"),
        ["Resource"] = ("Resource", "Ресурсы"),
        ["Tag"] = ("Tag", "Теги"),
        ["Check"] = ("Check", "Проверки"),
        ["General"] = ("General", "Общее"),
    };

    /// <summary>
    /// Get localized label for a condition function.
    /// Falls back to raw function name if not mapped.
    /// </summary>
    public static string GetLabel(string funcName, bool russian = false)
    {
        if (Functions.TryGetValue(funcName, out var label))
            return russian ? label.Ru : label.En;
        return funcName;
    }

    /// <summary>
    /// Get localized label for a surface type.
    /// Falls back to raw surface name (strips "Surface" prefix).
    /// </summary>
    public static string GetSurfaceLabel(string surfaceId, bool russian = false)
    {
        if (Surfaces.TryGetValue(surfaceId, out var label))
            return russian ? label.Ru : label.En;
        // Fallback: strip "Surface" prefix
        return surfaceId.StartsWith("Surface") ? surfaceId[7..] : surfaceId;
    }

    /// <summary>
    /// Get localized label for a category.
    /// </summary>
    public static string GetCategoryLabel(string category, bool russian = false)
    {
        if (Categories.TryGetValue(category, out var label))
            return russian ? label.Ru : label.En;
        return category;
    }
}
