using ParaTool.Core.Artifacts;
using Xunit;

namespace ParaTool.Tests;

public class CompilerValidatorTests
{
    private static ArtifactDefinition NewArmor(string statId = "TEST_Armor") => new()
    {
        StatId = statId,
        StatType = "Armor",
        UsingBase = "ARM_Gloves_Leather",
        Rarity = "Rare",
        LootPool = "Gloves",
        ValueOverride = 200,
        Unique = false,
        Weight = 0.5,
    };

    [Fact]
    public void Placeholder_YOURSTATUS_EmitsWarning()
    {
        var art = NewArmor();
        art.Boosts = "ApplyStatus(YOURSTATUS,100,1)";
        var r = ArtifactCompiler.Compile(art);
        Assert.Contains(r.Warnings, w => w.Contains("YOURSTATUS"));
    }

    [Fact]
    public void Placeholder_YourSpell_EmitsWarning()
    {
        var art = NewArmor();
        art.BoostsOnEquipMainHand = "UnlockSpell(YourSpell)";
        var r = ArtifactCompiler.Compile(art);
        Assert.Contains(r.Warnings, w => w.Contains("YourSpell"));
    }

    [Fact]
    public void Placeholder_Value_EmitsWarning()
    {
        var art = NewArmor();
        art.Boosts = "Tag(Value)";
        var r = ArtifactCompiler.Compile(art);
        Assert.Contains(r.Warnings, w => w.Contains("'Value'"));
    }

    [Fact]
    public void AutoGenerated_PassiveName_InPoE_EmitsWarning()
    {
        var art = NewArmor();
        art.PassivesOnEquip = "Passive_New_a1b2c3";
        var r = ArtifactCompiler.Compile(art);
        Assert.Contains(r.Warnings, w => w.Contains("auto-generated") && w.Contains("Passive_New_a1b2c3"));
    }

    [Fact]
    public void CleanArtifact_NoWarnings()
    {
        var art = NewArmor();
        art.Boosts = "AC(1);ProficiencyBonus(SavingThrow,Dexterity)";
        var r = ArtifactCompiler.Compile(art);
        Assert.Empty(r.Warnings);
    }

    [Fact]
    public void StatusGroup_SG_Frightened_NoWarning()
    {
        var art = NewArmor();
        art.Boosts = "StatusImmunity(SG_Frightened)";
        var r = ArtifactCompiler.Compile(art);
        Assert.DoesNotContain(r.Warnings, w => w.Contains("SG_Frightened"));
    }

    [Fact]
    public void Ability_CapZero_StrippedFromOutput()
    {
        var art = NewArmor();
        art.Boosts = "Ability(Constitution,1,0)";
        var r = ArtifactCompiler.Compile(art);
        Assert.Contains("Ability(Constitution,1)", r.StatsText);
        Assert.DoesNotContain("Ability(Constitution,1,0)", r.StatsText);
    }

    [Fact]
    public void Ability_CapNonZero_Preserved()
    {
        var art = NewArmor();
        art.Boosts = "Ability(Strength,2,24)";
        var r = ArtifactCompiler.Compile(art);
        Assert.Contains("Ability(Strength,2,24)", r.StatsText);
    }
}
