using System.Text;
using ParaTool.Core.Models;

namespace ParaTool.Core.Patching;

public static class StatsOverrideGenerator
{
    public static string Generate(IReadOnlyList<ItemEntry> items)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ParaTool — Stats Overrides");
        sb.AppendLine();

        foreach (var item in items)
        {
            if (!item.Enabled) continue;

            var pool = item.EffectivePool;
            var rarity = item.EffectiveRarity;
            var category = PricingGrid.GetSlotCategory(pool);
            var price = PricingGrid.GetPrice(category, rarity);

            sb.AppendLine($"new entry \"{item.StatId}\"");
            sb.AppendLine($"type \"{item.StatType}\"");
            sb.AppendLine($"using \"{item.StatId}\"");
            sb.AppendLine($"data \"ValueOverride\" \"{price}\"");
            sb.AppendLine("data \"Unique\" \"\"");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
