using System.Text;
using ParaTool.Core.Localization;
using ParaTool.Core.Schema;

namespace ParaTool.Core.Artifacts;

/// <summary>
/// Compiles ArtifactDefinition into BG3-ready files:
/// - Stats text (Armor/Weapon + PassiveData + StatusData + SpellData)
/// - Localization XML (English + Russian)
/// - RootTemplate data for LSF generation
///
/// Output is integrated into AMP pak during patching.
/// </summary>
public static class ArtifactCompiler
{
    /// <summary>
    /// Result of compiling an artifact — all generated file contents.
    /// </summary>
    public sealed class CompileResult
    {
        /// <summary>Stats text to append to AMP stat files.</summary>
        public required string StatsText { get; init; }

        /// <summary>Localization entries per language (lang → list of (handle, xmlText)).</summary>
        public required Dictionary<string, List<(string handle, string xmlText)>> LocalizationEntries { get; init; }

        /// <summary>RootTemplate UUID and parent UUID for LSF generation.</summary>
        public required string TemplateUuid { get; init; }
        public required string ParentTemplateUuid { get; init; }

        /// <summary>Custom icon DDS files (path → data), null if using atlas icon.</summary>
        public Dictionary<string, byte[]>? IconFiles { get; init; }

        /// <summary>
        /// Non-fatal warnings raised during compilation — placeholder strings left in chips,
        /// unrenamed auto-generated passive names, references to statuses that don't exist.
        /// The compile still succeeds; the caller decides how to surface these.
        /// </summary>
        public List<string> Warnings { get; init; } = [];
    }

    // ── Validators ──────────────────────────────────────────

    private static readonly string[] PlaceholderTokens = ["YOURSTATUS", "YourSpell"];

    private static readonly System.Text.RegularExpressions.Regex StatusRefRegex =
        new(@"\b(ApplyStatus|StatusImmunity|RemoveStatus|RemoveUniqueStatus)\s*\(\s*(?:(?:SELF|SWAP|OBSERVER_TARGET|OBSERVER_SOURCE|OWNER|TARGET)\s*,\s*)?([A-Z][A-Z0-9_]+)",
        System.Text.RegularExpressions.RegexOptions.Compiled);

    private static readonly System.Text.RegularExpressions.Regex AutoPassiveRegex =
        new(@"\bPassive_New_[0-9a-fA-F]{6,}\b", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static readonly System.Text.RegularExpressions.Regex BareValueRegex =
        new(@"[(,]\s*Value\s*[,)]", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static void ValidatePlaceholders(string artifactName, string fieldLabel, string value, List<string> warnings)
    {
        if (string.IsNullOrEmpty(value)) return;
        foreach (var ph in PlaceholderTokens)
            if (value.Contains(ph, StringComparison.Ordinal))
                warnings.Add($"[{artifactName}] {fieldLabel} contains placeholder '{ph}' — BG3 will ignore the boost. Replace before patching.");
        if (BareValueRegex.IsMatch(value))
            warnings.Add($"[{artifactName}] {fieldLabel} contains default placeholder 'Value' — fill the chip with a real value.");
    }

    private static void ValidateAutoGeneratedPassiveNames(string artifactName, string fieldLabel, string value, List<string> warnings)
    {
        if (string.IsNullOrEmpty(value)) return;
        foreach (System.Text.RegularExpressions.Match m in AutoPassiveRegex.Matches(value))
            warnings.Add($"[{artifactName}] {fieldLabel} references auto-generated passive '{m.Value}' — rename it to something meaningful before shipping.");
    }

    private static void ValidateStatusReferences(string artifactName, string fieldLabel, string value,
        Parsing.StatsResolver? resolver, List<string> warnings)
    {
        if (string.IsNullOrEmpty(value) || resolver == null) return;

        foreach (System.Text.RegularExpressions.Match m in StatusRefRegex.Matches(value))
        {
            var statusId = m.Groups[2].Value;
            // SG_* are built-in status groups — never defined as entries
            if (statusId.StartsWith("SG_", StringComparison.Ordinal)) continue;
            // Placeholders already flagged
            if (PlaceholderTokens.Contains(statusId, StringComparer.Ordinal)) continue;

            if (!resolver.AllEntries.ContainsKey(statusId)
                && Services.VanillaLocaService.GetPassive(statusId) == null)
            {
                warnings.Add($"[{artifactName}] {fieldLabel} references status '{statusId}' which does not exist in loaded mods or vanilla data — BG3 will silently skip this boost.");
            }
        }
    }

    /// <summary>
    /// True when a passive copy still points at the loca handle of the entry it was copied
    /// from — writing the user's edited text under that handle would change the original too.
    /// </summary>
    private static bool SharesHandle(IReadOnlyDictionary<string, string> sourceFields,
        string field, string? copyHandle)
    {
        if (string.IsNullOrEmpty(copyHandle)) return false;
        if (!sourceFields.TryGetValue(field, out var raw) || string.IsNullOrEmpty(raw)) return false;
        return HandleGenerator.Parse(raw).handle.Equals(copyHandle, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Compile a single artifact into BG3-ready content.
    /// </summary>
    public static CompileResult Compile(ArtifactDefinition art, bool isOverride = false,
        Parsing.StatsResolver? resolver = null)
    {
        var stats = new StringBuilder();
        var loca = new Dictionary<string, List<(string, string)>>
        {
            ["en"] = [],
            ["ru"] = []
        };
        var warnings = new List<string>();

        // ─── Main Item Stats ────────────────────────────
        stats.AppendLine($"new entry \"{art.StatId}\"");
        stats.AppendLine($"type \"{art.StatType}\"");
        stats.AppendLine($"using \"{art.UsingBase}\"");
        if (!isOverride && !string.IsNullOrEmpty(art.TemplateUuid))
            stats.AppendLine($"data \"RootTemplate\" \"{art.TemplateUuid}\"");
        // Write the equip Slot explicitly (armor AND weapons). The RootTemplate carries no
        // slot — it lives only in stats — and relying on the using-chain to inherit it is
        // fragile (load-order / missing parents), which is why items collapsed into the
        // Helmet slot. Emitting the resolved value makes the slot deterministic.
        // Fall back to resolving from the base for older artifacts saved without a Slot.
        var slotOut = art.Slot;
        if (string.IsNullOrEmpty(slotOut) && resolver != null && !string.IsNullOrEmpty(art.UsingBase))
            slotOut = resolver.Resolve(art.UsingBase, "Slot");
        if (!string.IsNullOrEmpty(slotOut))
            stats.AppendLine($"data \"Slot\" \"{slotOut}\"");

        // Over-insure equipment-type identity. BG3 resolves `using`-inheritance across
        // stat files/mods at load time, and it silently fails on bad load order or a
        // missing parent. When it does, the engine mis-classifies the item: e.g. a shield
        // whose `Shield "Yes"` did not inherit is treated as an off-hand WEAPON — held in
        // the hand instead of strapped, a versatile main-hand weapon goes two-handed, and
        // the wrong hold/animation set plays. Re-emit the base's identity/behaviour fields
        // explicitly so they no longer depend on inheritance. User-supplied values (written
        // further below) come after these, so they always win on duplicate keys.
        if (resolver != null && !string.IsNullOrEmpty(art.UsingBase))
        {
            var baseFields = resolver.ResolveAll(art.UsingBase);
            void ForceFromBase(string key, bool skip)
            {
                if (skip) return;
                if (baseFields.TryGetValue(key, out var v) && !string.IsNullOrEmpty(v))
                    stats.AppendLine($"data \"{key}\" \"{v}\"");
            }
            bool hasProf = !string.IsNullOrEmpty(art.ProficiencyGroup) && art.ProficiencyGroup != "None";
            if (art.StatType == "Armor")
            {
                ForceFromBase("Shield", skip: false);
                ForceFromBase("Armor Class Ability", skip: false);
                ForceFromBase("Proficiency Group", skip: hasProf);
            }
            else if (art.StatType == "Weapon")
            {
                ForceFromBase("Weapon Group", skip: false);
                ForceFromBase("Weapon Properties", skip: art.WeaponProperties != null);
                ForceFromBase("Proficiency Group", skip: hasProf);
                ForceFromBase("Damage Type", skip: !string.IsNullOrEmpty(art.DamageType) && art.DamageType != "None");
                ForceFromBase("Damage", skip: art.Damage != null);
                ForceFromBase("WeaponRange", skip: false);
                ForceFromBase("VersatileDamage", skip: art.VersatileDamage != null);
                ForceFromBase("Projectile", skip: false);
            }
        }

        stats.AppendLine($"data \"Rarity\" \"{art.Rarity}\"");
        // Ensure price matches rarity via PricingGrid (final safety net)
        var pool = art.LootPool ?? "Armor";
        var priceCat = Models.PricingGrid.GetSlotCategory(pool);
        var correctPrice = Models.PricingGrid.GetPrice(priceCat, art.Rarity);
        var price = art.ValueOverride > 0 ? art.ValueOverride : correctPrice;
        // If price looks like a default/stale value, use grid price
        if (price <= 200 && art.Rarity is "Rare" or "VeryRare" or "Legendary")
            price = correctPrice;
        stats.AppendLine($"data \"ValueOverride\" \"{price}\"");

        // Always write Unique explicitly to override inherited value from base
        stats.AppendLine($"data \"Unique\" \"{(art.Unique ? "1" : "")}\"");
        if (!string.IsNullOrEmpty(art.ComboCategory))
            stats.AppendLine($"data \"ComboCategory\" \"{art.ComboCategory}\"");
        if (art.Weight >= 0)
            stats.AppendLine($"data \"Weight\" \"{art.Weight.ToString(System.Globalization.CultureInfo.InvariantCulture)}\"");

        // Armor-specific — skip inherited defaults to not break slot/using chain
        if (art.ArmorClass >= 0)
            stats.AppendLine($"data \"ArmorClass\" \"{art.ArmorClass}\"");
        if (!string.IsNullOrEmpty(art.ArmorType) && art.ArmorType != "None")
            stats.AppendLine($"data \"ArmorType\" \"{art.ArmorType}\"");
        if (!string.IsNullOrEmpty(art.ProficiencyGroup) && art.ProficiencyGroup != "None")
            stats.AppendLine($"data \"Proficiency Group\" \"{art.ProficiencyGroup}\"");

        // Weapon-specific
        if (art.Damage != null)
            stats.AppendLine($"data \"Damage\" \"{art.Damage}\"");
        if (!string.IsNullOrEmpty(art.DamageType) && art.DamageType != "None")
            stats.AppendLine($"data \"Damage Type\" \"{art.DamageType}\"");
        if (art.VersatileDamage != null)
            stats.AppendLine($"data \"VersatileDamage\" \"{art.VersatileDamage}\"");
        if (art.DefaultBoosts != null)
        {
            var defaultBoosts = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(art.DefaultBoosts));
            ValidatePlaceholders(art.StatId, "DefaultBoosts", defaultBoosts, warnings);
            ValidateStatusReferences(art.StatId, "DefaultBoosts", defaultBoosts, resolver, warnings);
            stats.AppendLine($"data \"DefaultBoosts\" \"{defaultBoosts}\"");
        }
        if (art.WeaponProperties != null)
            stats.AppendLine($"data \"Weapon Properties\" \"{art.WeaponProperties}\"");

        // ─── Spell renaming (must run BEFORE Boosts is written) ───
        // A spell card cloned from an existing spell would overwrite that spell everywhere, so it
        // gets a per-artifact name that `using`s the original; the item's UnlockSpell list is
        // rewritten to the new name. A card set to edit the original keeps the name and
        // compiles as a self-`using` override instead.
        var spellRenames = RenameSpellCopies(art, resolver);
        // A spell granted through a passive (or typed into the item's Boosts) names the original
        // too; with a card for it, the item's version is the card.
        if (spellRenames.Count > 0)
        {
            art.Boosts = RewriteUnlockSpell(art.Boosts ?? "", spellRenames);
            foreach (var p in art.Passives)
                p.Boosts = RewriteUnlockSpell(p.Boosts ?? "", spellRenames);
        }

        // Mechanics — merge Boosts + SpellsOnEquip into single "Boosts" line
        var allBoosts = new List<string>();
        if (!string.IsNullOrEmpty(art.Boosts))
        {
            var removedBoosts = new HashSet<string>(art.RemovedBoosts ?? [], StringComparer.OrdinalIgnoreCase);
            var kept = art.Boosts
                .Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Where(b => !removedBoosts.Contains(b));
            var filteredBoosts = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(string.Join(";", kept)));
            if (!string.IsNullOrEmpty(filteredBoosts))
                allBoosts.Add(filteredBoosts);
        }
        if (!string.IsNullOrEmpty(art.SpellsOnEquip))
        {
            var removedSpells = new HashSet<string>(art.RemovedSpells ?? [], StringComparer.OrdinalIgnoreCase);
            var unlocked = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var spell in art.SpellsOnEquip.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                if (removedSpells.Contains(spell)) continue;
                if (spellRenames.TryGetValue(spell, out var renamedSpell) && removedSpells.Contains(renamedSpell)) continue;
                if (unlocked.Add(spell))
                    allBoosts.Add($"UnlockSpell({spell})");
            }
        }
        // Always write Boosts to override inherited value from base
        var boostsStr = string.Join(";", allBoosts);
        ValidatePlaceholders(art.StatId, "Boosts", boostsStr, warnings);
        ValidateStatusReferences(art.StatId, "Boosts", boostsStr, resolver, warnings);
        ValidateAutoGeneratedPassiveNames(art.StatId, "Boosts", boostsStr, warnings);
        stats.AppendLine($"data \"Boosts\" \"{boostsStr}\"");
        // Always write mainhand/offhand boosts (sanitized first)
        var mainHandBoosts = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(art.BoostsOnEquipMainHand ?? ""));
        var offHandBoosts = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(art.BoostsOnEquipOffHand ?? ""));
        ValidatePlaceholders(art.StatId, "BoostsOnEquipMainHand", mainHandBoosts, warnings);
        ValidateStatusReferences(art.StatId, "BoostsOnEquipMainHand", mainHandBoosts, resolver, warnings);
        ValidatePlaceholders(art.StatId, "BoostsOnEquipOffHand", offHandBoosts, warnings);
        ValidateStatusReferences(art.StatId, "BoostsOnEquipOffHand", offHandBoosts, resolver, warnings);
        stats.AppendLine($"data \"BoostsOnEquipMainHand\" \"{mainHandBoosts}\"");
        stats.AppendLine($"data \"BoostsOnEquipOffHand\" \"{offHandBoosts}\"");
        // ─── Passive renaming (must run BEFORE PassivesOnEquip is written) ───
        // A passive whose name doesn't belong to this artifact would overwrite the original
        // entry it was copied from, so it gets a unique per-artifact name. This has to happen
        // before the item header is emitted: PassivesOnEquip is built from these names, and
        // patching the already-rendered header by string replacement only ever matched a name
        // that filled the whole quoted field — any passive that was second in a ";"-joined list
        // kept its old name and became a dangling reference BG3 silently drops.
        var passiveRenames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        for (int pi = 0; pi < art.Passives.Count; pi++)
        {
            var p = art.Passives[pi];
            var originalName = p.Name;
            // If passive name doesn't start with artifact StatId, it's inherited — rename
            // Also rename when Name == UsingBase (existing passive added via picker)
            var needsRename = !originalName.StartsWith(art.StatId, StringComparison.OrdinalIgnoreCase)
                && (p.UsingBase == null || p.UsingBase.Equals(originalName, StringComparison.OrdinalIgnoreCase));
            if (needsRename)
            {
                // Only chain UsingBase → originalName if originalName actually exists in
                // BG3/mod data. Otherwise we'd emit `using "UnknownPassive"` which BG3
                // silently drops — pure-custom passive must stay UsingBase=null.
                var hasRealBase = resolver?.AllEntries.ContainsKey(originalName) == true
                                  || Services.VanillaLocaService.GetPassive(originalName) != null;

                var newName = $"{art.StatId}_Passive_{pi + 1}";
                passiveRenames[originalName] = newName;
                p.UsingBase = hasRealBase ? originalName : null;
                p.Name = newName;

                // A copy taken from another item used to inherit that item's loca handles, so
                // editing the copy's name or description rewrote the passive it came from.
                // Mint fresh handles for anything still carrying the source's.
                if (hasRealBase && resolver != null
                    && resolver.AllEntries.ContainsKey(originalName))
                {
                    var sourceFields = resolver.ResolveAll(originalName);
                    if (SharesHandle(sourceFields, "DisplayName", p.DisplayNameHandle))
                        p.DisplayNameHandle = HandleGenerator.New();
                    if (SharesHandle(sourceFields, "Description", p.DescriptionHandle))
                        p.DescriptionHandle = HandleGenerator.New();
                }
            }
        }
        if (passiveRenames.Count > 0 && !string.IsNullOrEmpty(art.PassivesOnEquip))
        {
            var poeParts = art.PassivesOnEquip.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            art.PassivesOnEquip = string.Join(";",
                poeParts.Select(n => passiveRenames.TryGetValue(n, out var renamed) ? renamed : n));
        }

        // Build PassivesOnEquip: merge explicit list + all passives from Passives array
        var poeNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (!string.IsNullOrEmpty(art.PassivesOnEquip))
            foreach (var n in art.PassivesOnEquip.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
                poeNames.Add(n);
        foreach (var p in art.Passives ?? [])
            if (!string.IsNullOrEmpty(p.Name))
                poeNames.Add(p.Name);
        // Tombstones: drop anything the user explicitly removed
        foreach (var removed in art.RemovedPassives ?? [])
        {
            poeNames.Remove(removed);
            if (passiveRenames.TryGetValue(removed, out var renamedRemoved))
                poeNames.Remove(renamedRemoved);
        }
        // Always write PassivesOnEquip to override inherited value from base
        var poeStr = string.Join(";", poeNames);
        ValidateAutoGeneratedPassiveNames(art.StatId, "PassivesOnEquip", poeStr, warnings);
        stats.AppendLine($"data \"PassivesOnEquip\" \"{poeStr}\"");
        // Always write StatusOnEquip to override inherited value (with tombstones applied)
        var statusOut = art.StatusOnEquip ?? "";
        if ((art.RemovedStatuses?.Count ?? 0) > 0 && !string.IsNullOrEmpty(statusOut))
        {
            var removedStatuses = new HashSet<string>(art.RemovedStatuses!, StringComparer.OrdinalIgnoreCase);
            var keptStatuses = statusOut
                .Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Where(s => !removedStatuses.Contains(s));
            statusOut = string.Join(";", keptStatuses);
        }
        ValidatePlaceholders(art.StatId, "StatusOnEquip", statusOut, warnings);
        stats.AppendLine($"data \"StatusOnEquip\" \"{statusOut}\"");

        stats.AppendLine();

        // ─── Passive Definitions ────────────────────────
        foreach (var passive in art.Passives)
        {
            // Sanitize legacy chip strings (strip Ability Cap=0 etc.) in place so
            // both the validation and the stats output see the fixed version.
            passive.Boosts = BoostMapping.SanitizeBoosts(passive.Boosts ?? "");
            passive.StatsFunctors = BoostMapping.SanitizeBoosts(passive.StatsFunctors ?? "");
            // Rewrite HasNoTags/HasAnyTags (which BG3 can't gate from a single tag) into
            // the proven not Tagged()/Tagged() form, so e.g. "Has No Tags SORCERER" works.
            passive.BoostConditions = ConditionSchema.NormalizeTagConditions(passive.BoostConditions ?? "");
            passive.Conditions = ConditionSchema.NormalizeTagConditions(passive.Conditions ?? "");
            // Repair condition dialect written by older builds — quoted enums and quoted
            // numbers, e.g. SavingThrow('Constitution','13') → SavingThrow(Ability.Constitution,13).
            // BG3 evaluates the quoted form as a string and the whole IF never fires.
            passive.BoostConditions = ConditionSchema.NormalizeConditionEnums(passive.BoostConditions);
            passive.Conditions = ConditionSchema.NormalizeConditionEnums(passive.Conditions);
            passive.Boosts = ConditionSchema.NormalizeConditionEnums(passive.Boosts);
            passive.StatsFunctors = ConditionSchema.NormalizeConditionEnums(passive.StatsFunctors);

            // Validate every chip-bearing field once per passive
            ValidatePlaceholders(passive.Name, "passive Boosts", passive.Boosts, warnings);
            ValidateStatusReferences(passive.Name, "passive Boosts", passive.Boosts, resolver, warnings);
            ValidatePlaceholders(passive.Name, "passive StatsFunctors", passive.StatsFunctors, warnings);
            ValidateStatusReferences(passive.Name, "passive StatsFunctors", passive.StatsFunctors, resolver, warnings);

            stats.AppendLine($"new entry \"{passive.Name}\"");
            stats.AppendLine("type \"PassiveData\"");
            // Skip self-referencing using (Name == UsingBase) — BG3 ignores it
            var hasUsing = passive.UsingBase != null
                && !passive.Name.Equals(passive.UsingBase, StringComparison.OrdinalIgnoreCase);
            if (hasUsing)
                stats.AppendLine($"using \"{passive.UsingBase}\"");

            // DisplayName/Description: only if handles exist
            if (!string.IsNullOrEmpty(passive.DisplayNameHandle))
                stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(passive.DisplayNameHandle)}\"");
            if (!string.IsNullOrEmpty(passive.DescriptionHandle))
                stats.AppendLine($"data \"Description\" \"{HandleGenerator.FormatWithVersion(passive.DescriptionHandle)}\"");

            // When using a base, always write ALL fields explicitly (even empty)
            // to override inherited values. Without this, cleared fields inherit from parent.
            if (hasUsing)
            {
                stats.AppendLine($"data \"DescriptionParams\" \"{passive.DescriptionParams}\"");
                stats.AppendLine($"data \"Properties\" \"{passive.Properties}\"");
                stats.AppendLine($"data \"BoostContext\" \"{passive.BoostContext}\"");
                stats.AppendLine($"data \"BoostConditions\" \"{passive.BoostConditions}\"");
                stats.AppendLine($"data \"Boosts\" \"{passive.Boosts}\"");
                stats.AppendLine($"data \"StatsFunctorContext\" \"{passive.StatsFunctorContext}\"");
                stats.AppendLine($"data \"Conditions\" \"{passive.Conditions}\"");
                stats.AppendLine($"data \"StatsFunctors\" \"{passive.StatsFunctors}\"");
            }
            else
            {
                // New passives (no using): only write non-empty fields
                if (!string.IsNullOrEmpty(passive.DescriptionParams))
                    stats.AppendLine($"data \"DescriptionParams\" \"{passive.DescriptionParams}\"");
                if (!string.IsNullOrEmpty(passive.Properties))
                    stats.AppendLine($"data \"Properties\" \"{passive.Properties}\"");
                if (!string.IsNullOrEmpty(passive.BoostContext))
                    stats.AppendLine($"data \"BoostContext\" \"{passive.BoostContext}\"");
                if (!string.IsNullOrEmpty(passive.BoostConditions))
                    stats.AppendLine($"data \"BoostConditions\" \"{passive.BoostConditions}\"");
                if (!string.IsNullOrEmpty(passive.Boosts))
                    stats.AppendLine($"data \"Boosts\" \"{passive.Boosts}\"");
                if (!string.IsNullOrEmpty(passive.StatsFunctorContext))
                    stats.AppendLine($"data \"StatsFunctorContext\" \"{passive.StatsFunctorContext}\"");
                if (!string.IsNullOrEmpty(passive.Conditions))
                    stats.AppendLine($"data \"Conditions\" \"{passive.Conditions}\"");
                if (!string.IsNullOrEmpty(passive.StatsFunctors))
                    stats.AppendLine($"data \"StatsFunctors\" \"{passive.StatsFunctors}\"");
            }

            stats.AppendLine();

            AddLocaEntries(loca, passive.DisplayName, passive.DisplayNameHandle);
            AddLocaEntries(loca, passive.Description, passive.DescriptionHandle);
        }

        // ─── Status Definitions ─────────────────────────
        foreach (var status in art.Statuses)
        {
            status.Boosts = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(status.Boosts ?? ""));
            ValidatePlaceholders(status.Name, "status Boosts", status.Boosts, warnings);
            ValidateStatusReferences(status.Name, "status Boosts", status.Boosts, resolver, warnings);

            stats.AppendLine($"new entry \"{status.Name}\"");
            stats.AppendLine("type \"StatusData\"");
            stats.AppendLine($"data \"StatusType\" \"{status.StatusType}\"");
            var statusHasUsing = status.UsingBase != null
                && !status.Name.Equals(status.UsingBase, StringComparison.OrdinalIgnoreCase);
            if (statusHasUsing)
                stats.AppendLine($"using \"{status.UsingBase}\"");

            stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(status.DisplayNameHandle)}\"");
            stats.AppendLine($"data \"Description\" \"{HandleGenerator.FormatWithVersion(status.DescriptionHandle)}\"");

            // When using a base, always write all fields to override inherited values
            if (statusHasUsing)
            {
                stats.AppendLine($"data \"DescriptionParams\" \"{status.DescriptionParams}\"");
                stats.AppendLine($"data \"Icon\" \"{status.Icon}\"");
                stats.AppendLine($"data \"StatusPropertyFlags\" \"{status.StatusPropertyFlags}\"");
                stats.AppendLine($"data \"StatusGroups\" \"{status.StatusGroups}\"");
                stats.AppendLine($"data \"StackType\" \"{status.StackType}\"");
                stats.AppendLine($"data \"StackPriority\" \"{status.StackPriority}\"");
                stats.AppendLine($"data \"Boosts\" \"{status.Boosts}\"");
                stats.AppendLine($"data \"PassivesOnApply\" \"{status.PassivesOnApply}\"");
                stats.AppendLine($"data \"RemoveEvents\" \"{status.RemoveEvents}\"");
                if (status.StatusEffect != null)
                    stats.AppendLine($"data \"StatusEffect\" \"{status.StatusEffect}\"");
            }
            else
            {
                if (!string.IsNullOrEmpty(status.DescriptionParams))
                    stats.AppendLine($"data \"DescriptionParams\" \"{status.DescriptionParams}\"");
                if (!string.IsNullOrEmpty(status.Icon))
                    stats.AppendLine($"data \"Icon\" \"{status.Icon}\"");
                if (!string.IsNullOrEmpty(status.StatusPropertyFlags))
                    stats.AppendLine($"data \"StatusPropertyFlags\" \"{status.StatusPropertyFlags}\"");
                if (!string.IsNullOrEmpty(status.StatusGroups))
                    stats.AppendLine($"data \"StatusGroups\" \"{status.StatusGroups}\"");
                if (!string.IsNullOrEmpty(status.StackType))
                    stats.AppendLine($"data \"StackType\" \"{status.StackType}\"");
                if (status.StackPriority != 0)
                    stats.AppendLine($"data \"StackPriority\" \"{status.StackPriority}\"");
                if (!string.IsNullOrEmpty(status.Boosts))
                    stats.AppendLine($"data \"Boosts\" \"{status.Boosts}\"");
                if (!string.IsNullOrEmpty(status.PassivesOnApply))
                    stats.AppendLine($"data \"PassivesOnApply\" \"{status.PassivesOnApply}\"");
                if (!string.IsNullOrEmpty(status.RemoveEvents))
                    stats.AppendLine($"data \"RemoveEvents\" \"{status.RemoveEvents}\"");
                if (status.StatusEffect != null)
                    stats.AppendLine($"data \"StatusEffect\" \"{status.StatusEffect}\"");
            }

            stats.AppendLine();

            AddLocaEntries(loca, status.DisplayName, status.DisplayNameHandle);
            AddLocaEntries(loca, status.Description, status.DescriptionHandle);
        }

        // ─── Summoned creature copies (named before spells are written) ───
        AssignSummonNames(art);
        var summonTemplates = art.Summons
            .Where(s => !string.IsNullOrEmpty(s.ParentTemplateUuid) && !string.IsNullOrEmpty(s.TemplateUuid))
            .GroupBy(s => s.ParentTemplateUuid, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.Last().TemplateUuid, StringComparer.OrdinalIgnoreCase);

        // ─── Spell Definitions ──────────────────────────
        var editedOriginals = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        // Each card, then its variants (the container is null for a card itself).
        var spellEntries = art.Spells.SelectMany(card =>
            card.Variants.Select(v => (spell: v, container: (SpellDefinition?)card)).Prepend((card, null)));
        foreach (var (spell, container) in spellEntries)
        {
            // Repair chip dialect only in fields the card changed. A field still equal to the base
            // is game syntax and goes out verbatim — the sanitizers reformat it (spacing, trailing
            // empty arguments) and a copy has to restate its original exactly.
            var spellBase = resolver != null && !string.IsNullOrEmpty(spell.UsingBase)
                ? resolver.ResolveAll(spell.UsingBase) : null;
            string? Repair(string key, string? value, Func<string, string> fix) =>
                value == null || (spellBase != null && spellBase.TryGetValue(key, out var inherited) && inherited == value)
                    ? value : fix(value);
            static string FixFunctors(string v) => ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(v));
            spell.SpellProperties = Repair("SpellProperties", spell.SpellProperties ?? "", FixFunctors)!;
            spell.SpellSuccess = Repair("SpellSuccess", spell.SpellSuccess, FixFunctors);
            spell.SpellFail = Repair("SpellFail", spell.SpellFail, FixFunctors);
            spell.TargetConditions = Repair("TargetConditions", spell.TargetConditions ?? "",
                v => ConditionSchema.NormalizeConditionEnums(ConditionSchema.NormalizeTagConditions(v)))!;
            spell.SpellRoll = Repair("SpellRoll", spell.SpellRoll, ConditionSchema.NormalizeConditionEnums);
            // Spawn the edited creature copies. After the repair step, so the rest of the
            // functor still goes out exactly as the game wrote it.
            if (summonTemplates.Count > 0)
            {
                spell.SpellProperties = RewriteSummons(spell.SpellProperties, summonTemplates)!;
                spell.SpellSuccess = RewriteSummons(spell.SpellSuccess, summonTemplates);
                spell.SpellFail = RewriteSummons(spell.SpellFail, summonTemplates);
            }
            foreach (var (label, value) in new[] {
                ("spell SpellProperties", spell.SpellProperties), ("spell SpellSuccess", spell.SpellSuccess ?? ""),
                ("spell SpellFail", spell.SpellFail ?? "") })
            {
                ValidatePlaceholders(spell.Name, label, value, warnings);
                ValidateStatusReferences(spell.Name, label, value, resolver, warnings);
            }

            if (string.IsNullOrEmpty(spell.SpellType) && resolver != null && spell.UsingBase != null)
                spell.SpellType = resolver.Resolve(spell.UsingBase, "SpellType") ?? spell.SpellType;

            // A variant follows its container's choice.
            var selfOverride = (container?.EditOriginal ?? spell.EditOriginal)
                && spell.UsingBase != null
                && spell.Name.Equals(spell.UsingBase, StringComparison.OrdinalIgnoreCase);
            if (selfOverride) editedOriginals.Add(spell.Name);

            stats.AppendLine($"new entry \"{spell.Name}\"");
            stats.AppendLine($"type \"SpellData\"");
            stats.AppendLine($"data \"SpellType\" \"{spell.SpellType}\"");
            // An edited original re-declares itself (`using "<self>"`), the form AMP uses to
            // rebalance vanilla spells; a copy points at the original under its own name.
            var spellHasUsing = spell.UsingBase != null
                && (selfOverride || !spell.Name.Equals(spell.UsingBase, StringComparison.OrdinalIgnoreCase));
            if (spellHasUsing)
                stats.AppendLine($"using \"{spell.UsingBase}\"");

            // An edited original whose text was left alone keeps the original handles, which the
            // game translates into every language; writing our copy of two languages under a new
            // handle would blank the rest.
            var keepName = selfOverride && !spell.DisplayNameEdited && !string.IsNullOrEmpty(spell.SourceDisplayNameHandle);
            var keepDesc = selfOverride && !spell.DescriptionEdited && !string.IsNullOrEmpty(spell.SourceDescriptionHandle);
            // Anything else writes its own text, so it must never do that under the source's handle.
            if (!keepName && (string.IsNullOrEmpty(spell.DisplayNameHandle) || SameHandle(spell.DisplayNameHandle, spell.SourceDisplayNameHandle)))
                spell.DisplayNameHandle = HandleGenerator.New();
            if (!keepDesc && (string.IsNullOrEmpty(spell.DescriptionHandle) || SameHandle(spell.DescriptionHandle, spell.SourceDescriptionHandle)))
                spell.DescriptionHandle = HandleGenerator.New();
            var nameHandle = keepName ? spell.SourceDisplayNameHandle! : spell.DisplayNameHandle;
            var descHandle = keepDesc ? spell.SourceDescriptionHandle! : spell.DescriptionHandle;

            stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(nameHandle)}\"");
            stats.AppendLine($"data \"Description\" \"{HandleGenerator.FormatWithVersion(descHandle)}\"");

            void Emit(string key, string? value, bool always)
            {
                if (value == null) return;
                if (always || value.Length > 0)
                    stats.AppendLine($"data \"{key}\" \"{value}\"");
            }
            // With a base, card fields are written even when empty so clearing a field on the card
            // clears it in game instead of inheriting it back. Null fields are not on the card.
            Emit("DescriptionParams", spell.DescriptionParams, spellHasUsing);
            Emit("Icon", string.IsNullOrEmpty(spell.Icon) ? null : spell.Icon, false);
            Emit("Level", spell.Level, spellHasUsing);
            Emit("SpellSchool", spell.SpellSchool, spellHasUsing);
            Emit("UseCosts", spell.UseCosts, spellHasUsing);
            Emit("Cooldown", spell.Cooldown, spellHasUsing);
            Emit("TargetRadius", spell.TargetRadius, spellHasUsing);
            Emit("AreaRadius", spell.AreaRadius, spellHasUsing);
            Emit("SpellRoll", spell.SpellRoll, spellHasUsing);
            Emit("SpellSuccess", spell.SpellSuccess, spellHasUsing);
            Emit("SpellFail", spell.SpellFail, spellHasUsing);
            Emit("SpellProperties", spell.SpellProperties, spellHasUsing);
            Emit("TargetConditions", spell.TargetConditions, spellHasUsing);
            Emit("SpellFlags", spell.SpellFlags, spellHasUsing);

            // Container links of a copy. Inherited through `using`, a copied container would list
            // the original variants and a copied variant would rejoin the original container, so
            // both directions are restated with the copies' names (the way AMP builds item
            // containers). An edited original keeps the links it has.
            if (!selfOverride && spellHasUsing)
            {
                string? Inherited(string key) => spellBase?.GetValueOrDefault(key) is { Length: > 0 } v ? v : null;
                if (spell.Variants.Count > 0)
                    Emit("ContainerSpells", string.Join(";", spell.Variants.Select(v => v.Name)), true);
                if (container != null)
                {
                    Emit("SpellContainerID", container.Name, true);
                    if (Inherited("ContainerSpells") != null) Emit("ContainerSpells", "", true);
                }
                else if (spell.Variants.Count == 0 && Inherited("SpellContainerID") != null)
                {
                    // A variant copied as a spell of its own leaves the original container.
                    Emit("SpellContainerID", "", true);
                    if (Inherited("ContainerSpells") != null) Emit("ContainerSpells", "", true);
                }
                // An upcast copy would otherwise group under the original spell it was cast up from.
                if ((container != null || spell.Variants.Count > 0 || Inherited("SpellContainerID") != null)
                    && Inherited("RootSpellID") != null)
                    Emit("RootSpellID", "", true);
            }

            foreach (var (key, value) in spell.ExtraData)
                stats.AppendLine($"data \"{key}\" \"{value}\"");

            stats.AppendLine();

            if (!keepName) AddLocaEntries(loca, spell.DisplayName, spell.DisplayNameHandle);
            if (!keepDesc) AddLocaEntries(loca, spell.Description, spell.DescriptionHandle);
        }

        // ─── Summoned creature stats ────────────────────
        foreach (var summon in art.Summons)
        {
            if (string.IsNullOrEmpty(summon.UsingBase) || string.IsNullOrEmpty(summon.StatsName)) continue;
            var creatureBase = resolver?.ResolveAll(summon.UsingBase);
            if (resolver != null && !resolver.AllEntries.ContainsKey(summon.UsingBase))
                warnings.Add($"[{art.StatId}] summon '{summon.StatsName}' uses unknown creature stats '{summon.UsingBase}'.");

            stats.AppendLine($"new entry \"{summon.StatsName}\"");
            stats.AppendLine("type \"Character\"");
            stats.AppendLine($"using \"{summon.UsingBase}\"");
            foreach (var (key, value) in summon.Stats)
            {
                var outValue = value ?? "";
                if (key == "DefaultBoosts" && !(creatureBase?.TryGetValue(key, out var inherited) == true && inherited == outValue))
                    outValue = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(outValue));
                stats.AppendLine($"data \"{key}\" \"{outValue}\"");
            }
            stats.AppendLine();

            if (summon.DisplayNameEdited)
                AddLocaEntries(loca, summon.DisplayName, summon.DisplayNameHandle);
        }

        // ─── Spell/Status Rename Overrides ─────────────────
        foreach (var (origId, names) in art.SpellRenames)
        {
            if (names.Count == 0) continue;
            // A spell card editing the original already declares this entry; a second
            // declaration would silently replace the card's changes.
            if (editedOriginals.Contains(origId))
            {
                warnings.Add($"[{art.StatId}] rename of spell '{origId}' ignored — the spell card editing it sets its name.");
                continue;
            }
            var handle = HandleGenerator.New();
            // Resolve SpellType from resolver (required for SpellData)
            var spellType = resolver?.Resolve(origId, "SpellType") ?? "Target";
            stats.AppendLine($"new entry \"{origId}\"");
            stats.AppendLine("type \"SpellData\"");
            stats.AppendLine($"data \"SpellType\" \"{spellType}\"");
            stats.AppendLine($"using \"{origId}\"");
            stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(handle)}\"");
            stats.AppendLine();
            AddLocaEntries(loca, names, handle);
        }
        foreach (var (origId, names) in art.StatusRenames)
        {
            if (names.Count == 0) continue;
            var handle = HandleGenerator.New();
            // Resolve StatusType from resolver (required for StatusData)
            var statusType = resolver?.Resolve(origId, "StatusType") ?? "BOOST";
            stats.AppendLine($"new entry \"{origId}\"");
            stats.AppendLine("type \"StatusData\"");
            stats.AppendLine($"data \"StatusType\" \"{statusType}\"");
            stats.AppendLine($"using \"{origId}\"");
            stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(handle)}\"");
            stats.AppendLine();
            AddLocaEntries(loca, names, handle);
        }

        // ─── Item Localization (stored in RootTemplate, not Stats) ──
        // We still generate loca entries — the RootTemplate LSF will
        // reference these handles for DisplayName/Description.
        AddLocaEntries(loca, art.DisplayName, art.DisplayNameHandle);
        AddLocaEntries(loca, art.Description, art.DescriptionHandle);

        // ─── Icons ──────────────────────────────────────
        Dictionary<string, byte[]>? iconFiles = null;
        if (art.IconMainDdsBase64 != null && art.IconConsoleDdsBase64 != null)
        {
            iconFiles = new Dictionary<string, byte[]>
            {
                [$"GUI/Assets/Tooltips/ItemIcons/{art.StatId}.DDS"] =
                    Convert.FromBase64String(art.IconMainDdsBase64),
                [$"GUI/Assets/ControllerUIIcons/items_png/{art.StatId}.DDS"] =
                    Convert.FromBase64String(art.IconConsoleDdsBase64),
            };
        }

        return new CompileResult
        {
            StatsText = stats.ToString(),
            LocalizationEntries = loca,
            TemplateUuid = art.TemplateUuid,
            ParentTemplateUuid = art.ParentTemplateUuid,
            IconFiles = iconFiles,
            Warnings = warnings,
        };
    }

    private static readonly System.Text.RegularExpressions.Regex UnlockSpellRegex =
        new(@"\bUnlockSpell\(\s*([A-Za-z0-9_]+)", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static string RewriteUnlockSpell(string boosts, IReadOnlyDictionary<string, string> renames) =>
        string.IsNullOrEmpty(boosts) ? boosts
            : UnlockSpellRegex.Replace(boosts, m => renames.TryGetValue(m.Groups[1].Value, out var renamed)
                ? $"UnlockSpell({renamed}" : m.Value);

    private static readonly System.Text.RegularExpressions.Regex SummonRegex =
        new(@"(\bSummon\(\s*)([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})",
            System.Text.RegularExpressions.RegexOptions.Compiled);

    /// <summary>Creature template UUIDs spawned by <c>Summon(…)</c> calls in functor text.</summary>
    public static IEnumerable<string> SummonedTemplates(string? functors) =>
        string.IsNullOrEmpty(functors) ? []
            : SummonRegex.Matches(functors).Select(m => m.Groups[2].Value);

    private static string? RewriteSummons(string? functors, IReadOnlyDictionary<string, string> templates) =>
        string.IsNullOrEmpty(functors) ? functors
            : SummonRegex.Replace(functors, m => templates.TryGetValue(m.Groups[2].Value, out var copy)
                ? m.Groups[1].Value + copy : m.Value);

    /// <summary>Names every summon's Character entry <c>{StatId}_Summon_{n}</c> (idempotent).</summary>
    public static void AssignSummonNames(ArtifactDefinition art)
    {
        var prefix = art.StatId + "_Summon_";
        var taken = new HashSet<string>(
            art.Summons.Select(s => s.StatsName).Where(n => n.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)),
            StringComparer.OrdinalIgnoreCase);
        int n = 1;
        foreach (var s in art.Summons)
        {
            if (s.StatsName.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) continue;
            string name;
            do name = $"{prefix}{n++}"; while (taken.Contains(name));
            taken.Add(name);
            s.StatsName = name;
        }
    }

    private static bool SameHandle(string? a, string? b) =>
        !string.IsNullOrEmpty(a) && !string.IsNullOrEmpty(b)
        && HandleGenerator.Parse(a).handle.Equals(HandleGenerator.Parse(b).handle, StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Gives every spell card copied from an existing spell a per-artifact name
    /// (<c>{StatId}_Spell_{n}</c>) that <c>using</c>s the original, and points the item's
    /// SpellsOnEquip at the new names. A card set to edit the original gets its original name
    /// back. Returns original name → name written.
    /// </summary>
    private static Dictionary<string, string> RenameSpellCopies(ArtifactDefinition art, Parsing.StatsResolver? resolver)
    {
        var renames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var taken = new HashSet<string>(art.Spells.Select(s => s.Name), StringComparer.OrdinalIgnoreCase);
        var copyPrefix = art.StatId + "_Spell_";

        for (int i = 0; i < art.Spells.Count; i++)
        {
            var sp = art.Spells[i];
            var currentName = sp.Name;

            if (sp.EditOriginal)
            {
                // Switched from copy to original after a compile had already renamed it.
                if (!string.IsNullOrEmpty(sp.UsingBase)
                    && !currentName.Equals(sp.UsingBase, StringComparison.OrdinalIgnoreCase)
                    && currentName.StartsWith(copyPrefix, StringComparison.OrdinalIgnoreCase))
                {
                    sp.Name = sp.UsingBase;
                    renames[currentName] = sp.Name;
                }
                continue;
            }

            var needsRename = !currentName.StartsWith(art.StatId, StringComparison.OrdinalIgnoreCase)
                && (sp.UsingBase == null || sp.UsingBase.Equals(currentName, StringComparison.OrdinalIgnoreCase));
            if (!needsRename) continue;

            // Chain `using` only to a spell that exists — `using "Unknown"` is silently dropped.
            var hasRealBase = resolver != null
                ? resolver.AllEntries.ContainsKey(currentName)
                : sp.UsingBase != null;

            string newName;
            int n = i + 1;
            do newName = $"{copyPrefix}{n++}"; while (taken.Contains(newName));
            taken.Add(newName);

            renames[currentName] = newName;
            sp.UsingBase = hasRealBase ? currentName : null;
            sp.Name = newName;

            if (hasRealBase && resolver != null)
            {
                var sourceFields = resolver.ResolveAll(currentName);
                if (SharesHandle(sourceFields, "DisplayName", sp.DisplayNameHandle))
                    sp.DisplayNameHandle = HandleGenerator.New();
                if (SharesHandle(sourceFields, "Description", sp.DescriptionHandle))
                    sp.DescriptionHandle = HandleGenerator.New();
            }
        }

        // Variants follow their container. A copy's variants are named after the container's current
        // name on every compile — the patcher compiles an artifact twice on the same objects, and
        // the second pass has nothing left to rename. An edited original's variants override theirs.
        foreach (var container in art.Spells)
        {
            for (int k = 0; k < container.Variants.Count; k++)
            {
                var v = container.Variants[k];
                var currentName = v.Name;
                if (container.EditOriginal)
                {
                    if (!string.IsNullOrEmpty(v.UsingBase) && !currentName.Equals(v.UsingBase, StringComparison.OrdinalIgnoreCase))
                    {
                        v.Name = v.UsingBase;
                        renames[currentName] = v.Name;
                    }
                    continue;
                }

                var target = $"{container.Name}_{k + 1}";
                if (currentName.Equals(target, StringComparison.OrdinalIgnoreCase)) continue;
                var original = v.UsingBase ?? currentName;
                var hasRealBase = resolver != null ? resolver.AllEntries.ContainsKey(original) : v.UsingBase != null;
                renames[currentName] = target;
                v.UsingBase = hasRealBase ? original : null;
                v.Name = target;
                if (hasRealBase && resolver != null)
                {
                    var sourceFields = resolver.ResolveAll(original);
                    if (SharesHandle(sourceFields, "DisplayName", v.DisplayNameHandle))
                        v.DisplayNameHandle = HandleGenerator.New();
                    if (SharesHandle(sourceFields, "Description", v.DescriptionHandle))
                        v.DescriptionHandle = HandleGenerator.New();
                }
            }
        }

        if (renames.Count > 0 && !string.IsNullOrEmpty(art.SpellsOnEquip))
        {
            art.SpellsOnEquip = string.Join(";",
                art.SpellsOnEquip.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                    .Select(s => renames.TryGetValue(s, out var renamed) ? renamed : s));
        }
        return renames;
    }

    /// <summary>
    /// Generate localization XML content for a specific language.
    /// </summary>
    public static string GenerateLocaXml(IReadOnlyList<(string handle, string xmlText)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        sb.AppendLine("<contentList>");
        foreach (var (handle, text) in entries)
        {
            sb.AppendLine($"  <content contentuid=\"{handle}\" version=\"1\">{text}</content>");
        }
        sb.AppendLine("</contentList>");
        return sb.ToString();
    }

    private static void AddLocaEntries(
        Dictionary<string, List<(string, string)>> loca,
        Dictionary<string, string> texts,
        string handle)
    {
        if (string.IsNullOrEmpty(handle)) return;

        foreach (var (lang, bbcode) in texts)
        {
            if (string.IsNullOrEmpty(bbcode)) continue;

            if (!loca.ContainsKey(lang))
                loca[lang] = [];

            var xmlText = BbCode.ToBg3Xml(bbcode);
            loca[lang].Add((handle, xmlText));
        }
    }
}
