using System.Text;
using ParaTool.Core.Localization;
using ParaTool.Core.Schema;

namespace ParaTool.Core.Artifacts;

/// <summary>
/// Compiles ArtifactDefinition into BG3-ready files:
/// - Stats text (Armor/Weapon + PassiveData + StatusData + SpellData)
/// - Localization XML (English + Russian)
/// - RootTemplate data for LSF generation
///
/// Output is integrated into AMP pak during patching.
/// </summary>
public static class ArtifactCompiler
{
    /// <summary>
    /// Result of compiling an artifact — all generated file contents.
    /// </summary>
    public sealed class CompileResult
    {
        /// <summary>Stats text to append to AMP stat files.</summary>
        public required string StatsText { get; init; }

        /// <summary>Localization entries per language (lang → list of (handle, xmlText)).</summary>
        public required Dictionary<string, List<(string handle, string xmlText)>> LocalizationEntries { get; init; }

        /// <summary>RootTemplate UUID and parent UUID for LSF generation.</summary>
        public required string TemplateUuid { get; init; }
        public required string ParentTemplateUuid { get; init; }

        /// <summary>Custom icon DDS files (path → data), null if using atlas icon.</summary>
        public Dictionary<string, byte[]>? IconFiles { get; init; }

        /// <summary>
        /// Non-fatal warnings raised during compilation — placeholder strings left in chips,
        /// unrenamed auto-generated passive names, references to statuses that don't exist.
        /// The compile still succeeds; the caller decides how to surface these.
        /// </summary>
        public List<string> Warnings { get; init; } = [];
    }

    // ── Validators ──────────────────────────────────────────

    private static readonly string[] PlaceholderTokens = ["YOURSTATUS", "YourSpell"];

    private static readonly System.Text.RegularExpressions.Regex StatusRefRegex =
        new(@"\b(ApplyStatus|StatusImmunity|RemoveStatus|RemoveUniqueStatus)\s*\(\s*(?:(?:SELF|SWAP|OBSERVER_TARGET|OBSERVER_SOURCE|OWNER|TARGET)\s*,\s*)?([A-Z][A-Z0-9_]+)",
        System.Text.RegularExpressions.RegexOptions.Compiled);

    private static readonly System.Text.RegularExpressions.Regex AutoPassiveRegex =
        new(@"\bPassive_New_[0-9a-fA-F]{6,}\b", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static readonly System.Text.RegularExpressions.Regex BareValueRegex =
        new(@"[(,]\s*Value\s*[,)]", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static void ValidatePlaceholders(string artifactName, string fieldLabel, string value, List<string> warnings)
    {
        if (string.IsNullOrEmpty(value)) return;
        foreach (var ph in PlaceholderTokens)
            if (value.Contains(ph, StringComparison.Ordinal))
                warnings.Add($"[{artifactName}] {fieldLabel} contains placeholder '{ph}' — BG3 will ignore the boost. Replace before patching.");
        if (BareValueRegex.IsMatch(value))
            warnings.Add($"[{artifactName}] {fieldLabel} contains default placeholder 'Value' — fill the chip with a real value.");
    }

    private static void ValidateAutoGeneratedPassiveNames(string artifactName, string fieldLabel, string value, List<string> warnings)
    {
        if (string.IsNullOrEmpty(value)) return;
        foreach (System.Text.RegularExpressions.Match m in AutoPassiveRegex.Matches(value))
            warnings.Add($"[{artifactName}] {fieldLabel} references auto-generated passive '{m.Value}' — rename it to something meaningful before shipping.");
    }

    private static void ValidateStatusReferences(string artifactName, string fieldLabel, string value,
        Parsing.StatsResolver? resolver, List<string> warnings, ISet<string>? ownStatuses = null)
    {
        if (string.IsNullOrEmpty(value) || resolver == null) return;

        foreach (System.Text.RegularExpressions.Match m in StatusRefRegex.Matches(value))
        {
            var statusId = m.Groups[2].Value;
            // SG_* are built-in status groups — never defined as entries
            if (statusId.StartsWith("SG_", StringComparison.Ordinal)) continue;
            // Placeholders already flagged
            if (PlaceholderTokens.Contains(statusId, StringComparer.Ordinal)) continue;
            // A status card of this artifact is written by this compile.
            if (ownStatuses?.Contains(statusId) == true) continue;

            if (!resolver.AllEntries.ContainsKey(statusId)
                && Services.VanillaLocaService.GetPassive(statusId) == null)
            {
                warnings.Add($"[{artifactName}] {fieldLabel} references status '{statusId}' which does not exist in loaded mods or vanilla data — BG3 will silently skip this boost.");
            }
        }
    }

    /// <summary>
    /// True when a passive copy still points at the loca handle of the entry it was copied
    /// from — writing the user's edited text under that handle would change the original too.
    /// </summary>
    private static bool SharesHandle(IReadOnlyDictionary<string, string> sourceFields,
        string field, string? copyHandle)
    {
        if (string.IsNullOrEmpty(copyHandle)) return false;
        if (!sourceFields.TryGetValue(field, out var raw) || string.IsNullOrEmpty(raw)) return false;
        return HandleGenerator.Parse(raw).handle.Equals(copyHandle, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Compile a single artifact into BG3-ready content.
    /// </summary>
    public static CompileResult Compile(ArtifactDefinition art, bool isOverride = false,
        Parsing.StatsResolver? resolver = null)
    {
        var stats = new StringBuilder();
        var loca = new Dictionary<string, List<(string, string)>>
        {
            ["en"] = [],
            ["ru"] = []
        };
        var warnings = new List<string>();

        // ─── Main Item Stats ────────────────────────────
        stats.AppendLine($"new entry \"{art.StatId}\"");
        stats.AppendLine($"type \"{art.StatType}\"");
        stats.AppendLine($"using \"{art.UsingBase}\"");
        if (!isOverride && !string.IsNullOrEmpty(art.TemplateUuid))
            stats.AppendLine($"data \"RootTemplate\" \"{art.TemplateUuid}\"");
        // Write the equip Slot explicitly (armor AND weapons). The RootTemplate carries no
        // slot — it lives only in stats — and relying on the using-chain to inherit it is
        // fragile (load-order / missing parents), which is why items collapsed into the
        // Helmet slot. Emitting the resolved value makes the slot deterministic.
        // Fall back to resolving from the base for older artifacts saved without a Slot.
        var slotOut = art.Slot;
        if (string.IsNullOrEmpty(slotOut) && resolver != null && !string.IsNullOrEmpty(art.UsingBase))
            slotOut = resolver.Resolve(art.UsingBase, "Slot");
        if (!string.IsNullOrEmpty(slotOut))
            stats.AppendLine($"data \"Slot\" \"{slotOut}\"");

        // Over-insure equipment-type identity. BG3 resolves `using`-inheritance across
        // stat files/mods at load time, and it silently fails on bad load order or a
        // missing parent. When it does, the engine mis-classifies the item: e.g. a shield
        // whose `Shield "Yes"` did not inherit is treated as an off-hand WEAPON — held in
        // the hand instead of strapped, a versatile main-hand weapon goes two-handed, and
        // the wrong hold/animation set plays. Re-emit the base's identity/behaviour fields
        // explicitly so they no longer depend on inheritance. User-supplied values (written
        // further below) come after these, so they always win on duplicate keys.
        if (resolver != null && !string.IsNullOrEmpty(art.UsingBase))
        {
            var baseFields = resolver.ResolveAll(art.UsingBase);
            void ForceFromBase(string key, bool skip)
            {
                if (skip) return;
                if (baseFields.TryGetValue(key, out var v) && !string.IsNullOrEmpty(v))
                    stats.AppendLine($"data \"{key}\" \"{v}\"");
            }
            bool hasProf = !string.IsNullOrEmpty(art.ProficiencyGroup) && art.ProficiencyGroup != "None";
            if (art.StatType == "Armor")
            {
                ForceFromBase("Shield", skip: false);
                ForceFromBase("Armor Class Ability", skip: false);
                ForceFromBase("Proficiency Group", skip: hasProf);
            }
            else if (art.StatType == "Weapon")
            {
                ForceFromBase("Weapon Group", skip: false);
                ForceFromBase("Weapon Properties", skip: art.WeaponProperties != null);
                ForceFromBase("Proficiency Group", skip: hasProf);
                ForceFromBase("Damage Type", skip: !string.IsNullOrEmpty(art.DamageType) && art.DamageType != "None");
                ForceFromBase("Damage", skip: art.Damage != null);
                ForceFromBase("WeaponRange", skip: false);
                ForceFromBase("VersatileDamage", skip: art.VersatileDamage != null);
                ForceFromBase("Projectile", skip: false);
            }
        }

        stats.AppendLine($"data \"Rarity\" \"{art.Rarity}\"");
        // Ensure price matches rarity via PricingGrid (final safety net)
        var pool = art.LootPool ?? "Armor";
        var priceCat = Models.PricingGrid.GetSlotCategory(pool);
        var correctPrice = Models.PricingGrid.GetPrice(priceCat, art.Rarity);
        var price = art.ValueOverride > 0 ? art.ValueOverride : correctPrice;
        // If price looks like a default/stale value, use grid price
        if (price <= 200 && art.Rarity is "Rare" or "VeryRare" or "Legendary")
            price = correctPrice;
        stats.AppendLine($"data \"ValueOverride\" \"{price}\"");

        // Always write Unique explicitly to override inherited value from base
        stats.AppendLine($"data \"Unique\" \"{(art.Unique ? "1" : "")}\"");
        if (!string.IsNullOrEmpty(art.ComboCategory))
            stats.AppendLine($"data \"ComboCategory\" \"{art.ComboCategory}\"");
        if (art.Weight >= 0)
            stats.AppendLine($"data \"Weight\" \"{art.Weight.ToString(System.Globalization.CultureInfo.InvariantCulture)}\"");

        // Armor-specific — skip inherited defaults to not break slot/using chain
        if (art.ArmorClass >= 0)
            stats.AppendLine($"data \"ArmorClass\" \"{art.ArmorClass}\"");
        if (!string.IsNullOrEmpty(art.ArmorType) && art.ArmorType != "None")
            stats.AppendLine($"data \"ArmorType\" \"{art.ArmorType}\"");
        if (!string.IsNullOrEmpty(art.ProficiencyGroup) && art.ProficiencyGroup != "None")
            stats.AppendLine($"data \"Proficiency Group\" \"{art.ProficiencyGroup}\"");

        // Weapon-specific
        if (art.Damage != null)
            stats.AppendLine($"data \"Damage\" \"{art.Damage}\"");
        if (!string.IsNullOrEmpty(art.DamageType) && art.DamageType != "None")
            stats.AppendLine($"data \"Damage Type\" \"{art.DamageType}\"");
        if (art.VersatileDamage != null)
            stats.AppendLine($"data \"VersatileDamage\" \"{art.VersatileDamage}\"");
        if (art.DefaultBoosts != null)
        {
            var defaultBoosts = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(art.DefaultBoosts));
            ValidatePlaceholders(art.StatId, "DefaultBoosts", defaultBoosts, warnings);
            ValidateStatusReferences(art.StatId, "DefaultBoosts", defaultBoosts, resolver, warnings);
            stats.AppendLine($"data \"DefaultBoosts\" \"{defaultBoosts}\"");
        }
        if (art.WeaponProperties != null)
            stats.AppendLine($"data \"Weapon Properties\" \"{art.WeaponProperties}\"");

        // ─── Spell renaming (must run BEFORE Boosts is written) ───
        // A spell card cloned from an existing spell would overwrite that spell everywhere, so it
        // gets a per-artifact name that `using`s the original; the item's UnlockSpell list is
        // rewritten to the new name. A card set to edit the original keeps the name and
        // compiles as a self-`using` override instead.
        var spellRenames = RenameSpellCopies(art, resolver);
        // A spell granted through a passive (or typed into the item's Boosts) names the original
        // too; with a card for it, the item's version is the card.
        if (spellRenames.Count > 0)
        {
            art.Boosts = RewriteUnlockSpell(art.Boosts ?? "", spellRenames);
            foreach (var p in art.Passives)
                p.Boosts = RewriteUnlockSpell(p.Boosts ?? "", spellRenames);
        }
        // Status cards the same way: a copy gets its own name, and everything on this item that
        // applies, removes or checks the original (functors, conditions, StatusOnEquip) is pointed
        // at the copy — with a card for it, the item's version of the status is the card.
        var statusRenames = RenameStatusCopies(art, resolver);
        if (statusRenames.Count > 0)
            RewriteStatusReferences(art, statusRenames);
        // Original → copy for every status copy on this item. Unlike the renames it holds on the
        // second compile of the same object too (the one the patcher writes), when nothing is left
        // to rename: text inherited from a base is compared and rewritten through this.
        var statusCopies = new Dictionary<string, string>(statusRenames, StringComparer.OrdinalIgnoreCase);
        foreach (var st in art.Statuses)
            if (!st.EditOriginal && !string.IsNullOrEmpty(st.UsingBase) && !st.UsingBase.Equals(st.Name, StringComparison.OrdinalIgnoreCase))
                statusCopies.TryAdd(st.UsingBase, st.Name);
        var ownStatuses = new HashSet<string>(art.Statuses.Select(s => s.Name), StringComparer.OrdinalIgnoreCase);

        // Mechanics — merge Boosts + SpellsOnEquip into single "Boosts" line
        var allBoosts = new List<string>();
        if (!string.IsNullOrEmpty(art.Boosts))
        {
            var removedBoosts = new HashSet<string>(art.RemovedBoosts ?? [], StringComparer.OrdinalIgnoreCase);
            var kept = BoostMapping.SplitBoostList(art.Boosts)
                .Where(b => !removedBoosts.Contains(b));
            var filteredBoosts = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(string.Join(";", kept)));
            if (!string.IsNullOrEmpty(filteredBoosts))
                allBoosts.Add(filteredBoosts);
        }
        if (!string.IsNullOrEmpty(art.SpellsOnEquip))
        {
            var removedSpells = new HashSet<string>(art.RemovedSpells ?? [], StringComparer.OrdinalIgnoreCase);
            var removedCopies = new HashSet<string>(art.Spells
                .Where(sp => !sp.EditOriginal && !string.IsNullOrEmpty(sp.UsingBase) && removedSpells.Contains(sp.UsingBase)
                             && sp.Name.StartsWith(art.StatId + "_Spell_", StringComparison.OrdinalIgnoreCase))
                .Select(sp => sp.Name), StringComparer.OrdinalIgnoreCase);
            var unlocked = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var spell in art.SpellsOnEquip.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                if (removedSpells.Contains(spell)) continue;
                if (spellRenames.TryGetValue(spell, out var renamedSpell) && removedSpells.Contains(renamedSpell)) continue;
                // A copy the first pass named: its tombstone is still under the original's name.
                if (removedCopies.Contains(spell)) continue;
                if (unlocked.Add(spell))
                    allBoosts.Add($"UnlockSpell({spell})");
            }
        }
        // Always write Boosts to override inherited value from base
        var boostsStr = string.Join(";", allBoosts);
        ValidatePlaceholders(art.StatId, "Boosts", boostsStr, warnings);
        ValidateStatusReferences(art.StatId, "Boosts", boostsStr, resolver, warnings, ownStatuses);
        ValidateAutoGeneratedPassiveNames(art.StatId, "Boosts", boostsStr, warnings);
        stats.AppendLine($"data \"Boosts\" \"{boostsStr}\"");
        // Always write mainhand/offhand boosts (sanitized first)
        var mainHandBoosts = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(art.BoostsOnEquipMainHand ?? ""));
        var offHandBoosts = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(art.BoostsOnEquipOffHand ?? ""));
        ValidatePlaceholders(art.StatId, "BoostsOnEquipMainHand", mainHandBoosts, warnings);
        ValidateStatusReferences(art.StatId, "BoostsOnEquipMainHand", mainHandBoosts, resolver, warnings, ownStatuses);
        ValidatePlaceholders(art.StatId, "BoostsOnEquipOffHand", offHandBoosts, warnings);
        ValidateStatusReferences(art.StatId, "BoostsOnEquipOffHand", offHandBoosts, resolver, warnings, ownStatuses);
        stats.AppendLine($"data \"BoostsOnEquipMainHand\" \"{mainHandBoosts}\"");
        stats.AppendLine($"data \"BoostsOnEquipOffHand\" \"{offHandBoosts}\"");
        // ─── Passive renaming (must run BEFORE PassivesOnEquip is written) ───
        // A passive whose name doesn't belong to this artifact would overwrite the original
        // entry it was copied from, so it gets a unique per-artifact name. This has to happen
        // before the item header is emitted: PassivesOnEquip is built from these names, and
        // patching the already-rendered header by string replacement only ever matched a name
        // that filled the whole quoted field — any passive that was second in a ";"-joined list
        // kept its old name and became a dangling reference BG3 silently drops.
        var passiveRenames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var passivePrefix = art.StatId + "_Passive_";
        var passiveNames = new HashSet<string>(art.Passives.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);
        for (int pi = 0; pi < art.Passives.Count; pi++)
        {
            var p = art.Passives[pi];
            var originalName = p.Name;
            // If passive name doesn't start with artifact StatId, it's inherited — rename
            // Also rename when Name == UsingBase (existing passive added via picker)
            var needsRename = !originalName.StartsWith(art.StatId, StringComparison.OrdinalIgnoreCase)
                && (p.UsingBase == null || p.UsingBase.Equals(originalName, StringComparison.OrdinalIgnoreCase));
            // A copy another artifact's compile already named (a duplicate of a compiled artifact):
            // still a copy of its UsingBase, only under a name the other artifact declares too.
            var foreignCopy = !needsRename && !string.IsNullOrEmpty(p.UsingBase)
                && !p.UsingBase.Equals(originalName, StringComparison.OrdinalIgnoreCase)
                && IsOtherArtifactsCopyName(originalName, "_Passive_", art.StatId);
            if (foreignCopy)
            {
                var copyName = NextFreeName(passivePrefix, pi + 1, passiveNames);
                passiveRenames[originalName] = copyName;
                p.Name = copyName;
            }
            else if (needsRename)
            {
                // Only chain UsingBase → originalName if originalName actually exists in
                // BG3/mod data. Otherwise we'd emit `using "UnknownPassive"` which BG3
                // silently drops — pure-custom passive must stay UsingBase=null.
                var hasRealBase = resolver?.AllEntries.ContainsKey(originalName) == true
                                  || Services.VanillaLocaService.GetPassive(originalName) != null;

                var newName = NextFreeName(passivePrefix, pi + 1, passiveNames);
                passiveRenames[originalName] = newName;
                p.UsingBase = hasRealBase ? originalName : null;
                p.Name = newName;

                // A copy taken from another item used to inherit that item's loca handles, so
                // editing the copy's name or description rewrote the passive it came from.
                // Mint fresh handles for anything still carrying the source's.
                if (hasRealBase && resolver != null
                    && resolver.AllEntries.ContainsKey(originalName))
                {
                    var sourceFields = resolver.ResolveAll(originalName);
                    if (SharesHandle(sourceFields, "DisplayName", p.DisplayNameHandle))
                        p.DisplayNameHandle = HandleGenerator.New();
                    if (SharesHandle(sourceFields, "Description", p.DescriptionHandle))
                        p.DescriptionHandle = HandleGenerator.New();
                }
            }
        }
        if (passiveRenames.Count > 0 && !string.IsNullOrEmpty(art.PassivesOnEquip))
        {
            var poeParts = art.PassivesOnEquip.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            art.PassivesOnEquip = string.Join(";",
                poeParts.Select(n => passiveRenames.TryGetValue(n, out var renamed) ? renamed : n));
        }

        // Build PassivesOnEquip: merge explicit list + all passives from Passives array
        var poeNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (!string.IsNullOrEmpty(art.PassivesOnEquip))
            foreach (var n in art.PassivesOnEquip.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
                poeNames.Add(n);
        foreach (var p in art.Passives ?? [])
            if (!string.IsNullOrEmpty(p.Name))
                poeNames.Add(p.Name);
        // Tombstones: drop anything the user explicitly removed. A passive card is always
        // equipped, so a tombstone never hides one: deleting a card removes it from the list, and
        // a tombstone left under a card's name is stale (a passive deleted, then made again under
        // the same name). Ignoring it only on the first pass would differ from the second, which
        // no longer sees the card's old name.
        foreach (var removed in art.RemovedPassives ?? [])
        {
            if (passiveRenames.ContainsKey(removed)
                || art.Passives.Any(p => p.Name.Equals(removed, StringComparison.OrdinalIgnoreCase)))
                continue;
            poeNames.Remove(removed);
        }
        // Always write PassivesOnEquip to override inherited value from base
        var poeStr = string.Join(";", poeNames);
        ValidateAutoGeneratedPassiveNames(art.StatId, "PassivesOnEquip", poeStr, warnings);
        stats.AppendLine($"data \"PassivesOnEquip\" \"{poeStr}\"");
        // Always write StatusOnEquip to override inherited value (with tombstones applied)
        var statusOut = art.StatusOnEquip ?? "";
        if ((art.RemovedStatuses?.Count ?? 0) > 0 && !string.IsNullOrEmpty(statusOut))
        {
            var removedStatuses = new HashSet<string>(art.RemovedStatuses!, StringComparer.OrdinalIgnoreCase);
            var keptStatuses = statusOut
                .Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Where(s => !removedStatuses.Contains(s));
            statusOut = string.Join(";", keptStatuses);
        }
        ValidatePlaceholders(art.StatId, "StatusOnEquip", statusOut, warnings);
        stats.AppendLine($"data \"StatusOnEquip\" \"{statusOut}\"");

        stats.AppendLine();

        // ─── Passive Definitions ────────────────────────
        foreach (var passive in art.Passives)
        {
            // Sanitize legacy chip strings (strip Ability Cap=0 etc.) in place so
            // both the validation and the stats output see the fixed version.
            passive.Boosts = BoostMapping.SanitizeBoosts(passive.Boosts ?? "");
            passive.StatsFunctors = BoostMapping.SanitizeBoosts(passive.StatsFunctors ?? "");
            // Rewrite HasNoTags/HasAnyTags (which BG3 can't gate from a single tag) into
            // the proven not Tagged()/Tagged() form, so e.g. "Has No Tags SORCERER" works.
            passive.BoostConditions = ConditionSchema.NormalizeTagConditions(passive.BoostConditions ?? "");
            passive.Conditions = ConditionSchema.NormalizeTagConditions(passive.Conditions ?? "");
            // Repair condition dialect written by older builds — quoted enums and quoted
            // numbers, e.g. SavingThrow('Constitution','13') → SavingThrow(Ability.Constitution,13).
            // BG3 evaluates the quoted form as a string and the whole IF never fires.
            passive.BoostConditions = ConditionSchema.NormalizeConditionEnums(passive.BoostConditions);
            passive.Conditions = ConditionSchema.NormalizeConditionEnums(passive.Conditions);
            passive.Boosts = ConditionSchema.NormalizeConditionEnums(passive.Boosts);
            passive.StatsFunctors = ConditionSchema.NormalizeConditionEnums(passive.StatsFunctors);

            // Validate every chip-bearing field once per passive
            ValidatePlaceholders(passive.Name, "passive Boosts", passive.Boosts, warnings);
            ValidateStatusReferences(passive.Name, "passive Boosts", passive.Boosts, resolver, warnings, ownStatuses);
            ValidatePlaceholders(passive.Name, "passive StatsFunctors", passive.StatsFunctors, warnings);
            ValidateStatusReferences(passive.Name, "passive StatsFunctors", passive.StatsFunctors, resolver, warnings, ownStatuses);

            stats.AppendLine($"new entry \"{passive.Name}\"");
            stats.AppendLine("type \"PassiveData\"");
            // Skip self-referencing using (Name == UsingBase) — BG3 ignores it
            var hasUsing = passive.UsingBase != null
                && !passive.Name.Equals(passive.UsingBase, StringComparison.OrdinalIgnoreCase);
            if (hasUsing)
                stats.AppendLine($"using \"{passive.UsingBase}\"");

            // DisplayName/Description: only if handles exist
            if (!string.IsNullOrEmpty(passive.DisplayNameHandle))
                stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(passive.DisplayNameHandle)}\"");
            if (!string.IsNullOrEmpty(passive.DescriptionHandle))
                stats.AppendLine($"data \"Description\" \"{HandleGenerator.FormatWithVersion(passive.DescriptionHandle)}\"");

            // When using a base, always write ALL fields explicitly (even empty)
            // to override inherited values. Without this, cleared fields inherit from parent.
            if (hasUsing)
            {
                stats.AppendLine($"data \"DescriptionParams\" \"{passive.DescriptionParams}\"");
                stats.AppendLine($"data \"Properties\" \"{passive.Properties}\"");
                stats.AppendLine($"data \"BoostContext\" \"{passive.BoostContext}\"");
                stats.AppendLine($"data \"BoostConditions\" \"{passive.BoostConditions}\"");
                stats.AppendLine($"data \"Boosts\" \"{passive.Boosts}\"");
                stats.AppendLine($"data \"StatsFunctorContext\" \"{passive.StatsFunctorContext}\"");
                stats.AppendLine($"data \"Conditions\" \"{passive.Conditions}\"");
                stats.AppendLine($"data \"StatsFunctors\" \"{passive.StatsFunctors}\"");
            }
            else
            {
                // New passives (no using): only write non-empty fields
                if (!string.IsNullOrEmpty(passive.DescriptionParams))
                    stats.AppendLine($"data \"DescriptionParams\" \"{passive.DescriptionParams}\"");
                if (!string.IsNullOrEmpty(passive.Properties))
                    stats.AppendLine($"data \"Properties\" \"{passive.Properties}\"");
                if (!string.IsNullOrEmpty(passive.BoostContext))
                    stats.AppendLine($"data \"BoostContext\" \"{passive.BoostContext}\"");
                if (!string.IsNullOrEmpty(passive.BoostConditions))
                    stats.AppendLine($"data \"BoostConditions\" \"{passive.BoostConditions}\"");
                if (!string.IsNullOrEmpty(passive.Boosts))
                    stats.AppendLine($"data \"Boosts\" \"{passive.Boosts}\"");
                if (!string.IsNullOrEmpty(passive.StatsFunctorContext))
                    stats.AppendLine($"data \"StatsFunctorContext\" \"{passive.StatsFunctorContext}\"");
                if (!string.IsNullOrEmpty(passive.Conditions))
                    stats.AppendLine($"data \"Conditions\" \"{passive.Conditions}\"");
                if (!string.IsNullOrEmpty(passive.StatsFunctors))
                    stats.AppendLine($"data \"StatsFunctors\" \"{passive.StatsFunctors}\"");
            }

            stats.AppendLine();

            AddLocaEntries(loca, passive.DisplayName, passive.DisplayNameHandle);
            AddLocaEntries(loca, passive.Description, passive.DescriptionHandle);
        }

        // ─── Status Definitions ─────────────────────────
        var editedOriginalStatuses = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var status in art.Statuses)
        {
            // Same rule as spell cards: chip dialect is repaired only in fields the card changed.
            var statusBase = resolver != null && !string.IsNullOrEmpty(status.UsingBase)
                ? resolver.ResolveAll(status.UsingBase) : null;
            // The base as this artifact sees it: its mentions of renamed statuses already point at the copies.
            string? Repair(string key, string? value, Func<string, string> fix) =>
                value == null || (statusBase != null && statusBase.TryGetValue(key, out var inherited)
                                  && RewriteStatusText(inherited, statusCopies) == value)
                    ? value : fix(value);
            static string FixFunctors(string v) => ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(v));
            static string FixConditions(string v) => ConditionSchema.NormalizeConditionEnums(ConditionSchema.NormalizeTagConditions(v));
            status.Boosts = Repair("Boosts", status.Boosts ?? "", FixFunctors)!;
            status.TickFunctors = Repair("TickFunctors", status.TickFunctors, FixFunctors);
            status.OnApplyFunctors = Repair("OnApplyFunctors", status.OnApplyFunctors, FixFunctors);
            status.OnRemoveFunctors = Repair("OnRemoveFunctors", status.OnRemoveFunctors, FixFunctors);
            status.AuraStatuses = Repair("AuraStatuses", status.AuraStatuses, FixFunctors);
            status.RemoveConditions = Repair("RemoveConditions", status.RemoveConditions, FixConditions);
            foreach (var (label, value) in new[] {
                ("status Boosts", status.Boosts), ("status TickFunctors", status.TickFunctors ?? ""),
                ("status OnApplyFunctors", status.OnApplyFunctors ?? ""), ("status OnRemoveFunctors", status.OnRemoveFunctors ?? ""),
                ("status AuraStatuses", status.AuraStatuses ?? "") })
            {
                ValidatePlaceholders(status.Name, label, value, warnings);
                ValidateStatusReferences(status.Name, label, value, resolver, warnings, ownStatuses);
            }

            var selfOverride = status.EditOriginal && status.UsingBase != null
                && status.Name.Equals(status.UsingBase, StringComparison.OrdinalIgnoreCase);
            if (selfOverride) editedOriginalStatuses.Add(status.Name);

            stats.AppendLine($"new entry \"{status.Name}\"");
            stats.AppendLine("type \"StatusData\"");
            stats.AppendLine($"data \"StatusType\" \"{status.StatusType}\"");
            var statusHasUsing = status.UsingBase != null
                && (selfOverride || !status.Name.Equals(status.UsingBase, StringComparison.OrdinalIgnoreCase));
            if (statusHasUsing)
                stats.AppendLine($"using \"{status.UsingBase}\"");

            // Text the card left alone stays the original's: its handle is translated into every
            // language the game ships, where a copy of our two would blank the rest. Edited text is
            // written under handles of the card's own, never under the source's.
            var keepName = statusHasUsing && !status.DisplayNameEdited && !string.IsNullOrEmpty(status.SourceDisplayNameHandle);
            var keepDesc = statusHasUsing && !status.DescriptionEdited && !string.IsNullOrEmpty(status.SourceDescriptionHandle);
            if (!keepName && (string.IsNullOrEmpty(status.DisplayNameHandle) || SameHandle(status.DisplayNameHandle, status.SourceDisplayNameHandle)))
                status.DisplayNameHandle = HandleGenerator.New();
            if (!keepDesc && (string.IsNullOrEmpty(status.DescriptionHandle) || SameHandle(status.DescriptionHandle, status.SourceDescriptionHandle)))
                status.DescriptionHandle = HandleGenerator.New();
            // No text at all (a hidden status) writes no name: the game shows none, or the original's.
            if (keepName || status.DisplayName.Values.Any(v => !string.IsNullOrEmpty(v)))
                stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(keepName ? status.SourceDisplayNameHandle! : status.DisplayNameHandle)}\"");
            if (keepDesc || status.Description.Values.Any(v => !string.IsNullOrEmpty(v)))
                stats.AppendLine($"data \"Description\" \"{HandleGenerator.FormatWithVersion(keepDesc ? status.SourceDescriptionHandle! : status.DescriptionHandle)}\"");

            void Emit(string key, string? value, bool always)
            {
                if (value == null) return;
                if (always || value.Length > 0)
                    stats.AppendLine($"data \"{key}\" \"{value}\"");
            }
            // With a base, card fields are written even when empty so clearing one clears it in game.
            Emit("DescriptionParams", status.DescriptionParams, statusHasUsing);
            Emit("Icon", string.IsNullOrEmpty(status.Icon) ? null : status.Icon, false);
            Emit("StackId", status.StackId, statusHasUsing);
            Emit("StackType", status.StackType, statusHasUsing);
            Emit("StackPriority", status.StackPriority?.ToString(System.Globalization.CultureInfo.InvariantCulture), statusHasUsing);
            Emit("StatusPropertyFlags", status.StatusPropertyFlags, statusHasUsing);
            Emit("StatusGroups", status.StatusGroups, statusHasUsing);
            Emit("Boosts", status.Boosts, statusHasUsing);
            Emit("Passives", status.Passives ?? (string.IsNullOrEmpty(status.PassivesOnApply) ? null : status.PassivesOnApply), statusHasUsing);
            Emit("TickType", status.TickType, statusHasUsing);
            Emit("TickFunctors", status.TickFunctors, statusHasUsing);
            Emit("OnApplyFunctors", status.OnApplyFunctors, statusHasUsing);
            Emit("OnRemoveFunctors", status.OnRemoveFunctors, statusHasUsing);
            Emit("RemoveConditions", status.RemoveConditions, statusHasUsing);
            Emit("RemoveEvents", status.RemoveEvents, statusHasUsing);
            Emit("AuraRadius", status.AuraRadius, statusHasUsing);
            Emit("AuraStatuses", status.AuraStatuses, statusHasUsing);
            if (status.StatusEffect != null)
                stats.AppendLine($"data \"StatusEffect\" \"{status.StatusEffect}\"");
            // Fields not on the card stay inherited — except where the base names a status this
            // item has a copy of, itself most often (PHANTASMAL_KILLER ends by RemoveStatus(PHANTASMAL_KILLER)
            // in OnTickFail). The copy restates those pointed at the copy, or it would remove, check
            // or apply the original instead and never end.
            if (statusHasUsing && !selfOverride && statusBase != null)
                foreach (var key in InheritedStatusTextFields)
                    if (statusBase.TryGetValue(key, out var inherited)
                        && RewriteStatusText(inherited, statusCopies) is { } pointed && pointed != inherited)
                        stats.AppendLine($"data \"{key}\" \"{pointed}\"");

            stats.AppendLine();

            if (!keepName) AddLocaEntries(loca, status.DisplayName, status.DisplayNameHandle);
            if (!keepDesc) AddLocaEntries(loca, status.Description, status.DescriptionHandle);
        }

        // ─── Summoned creature copies (named before spells are written) ───
        AssignSummonNames(art);
        var summonTemplates = art.Summons
            .Where(s => !string.IsNullOrEmpty(s.ParentTemplateUuid) && !string.IsNullOrEmpty(s.TemplateUuid))
            .GroupBy(s => s.ParentTemplateUuid, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.Last().TemplateUuid, StringComparer.OrdinalIgnoreCase);

        // ─── Spell Definitions ──────────────────────────
        var editedOriginals = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        // Each card, then its variants (the container is null for a card itself).
        var spellEntries = art.Spells.SelectMany(card =>
            card.Variants.Select(v => (spell: v, container: (SpellDefinition?)card)).Prepend((card, null)));
        foreach (var (spell, container) in spellEntries)
        {
            // Repair chip dialect only in fields the card changed. A field still equal to the base
            // is game syntax and goes out verbatim — the sanitizers reformat it (spacing, trailing
            // empty arguments) and a copy has to restate its original exactly.
            var spellBase = resolver != null && !string.IsNullOrEmpty(spell.UsingBase)
                ? resolver.ResolveAll(spell.UsingBase) : null;
            string? Repair(string key, string? value, Func<string, string> fix) =>
                value == null || (spellBase != null && spellBase.TryGetValue(key, out var inherited)
                                  && RewriteStatusText(inherited, statusCopies) == value)
                    ? value : fix(value);
            static string FixFunctors(string v) => ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(v));
            spell.SpellProperties = Repair("SpellProperties", spell.SpellProperties ?? "", FixFunctors)!;
            spell.SpellSuccess = Repair("SpellSuccess", spell.SpellSuccess, FixFunctors);
            spell.SpellFail = Repair("SpellFail", spell.SpellFail, FixFunctors);
            spell.TargetConditions = Repair("TargetConditions", spell.TargetConditions ?? "",
                v => ConditionSchema.NormalizeConditionEnums(ConditionSchema.NormalizeTagConditions(v)))!;
            spell.SpellRoll = Repair("SpellRoll", spell.SpellRoll, ConditionSchema.NormalizeConditionEnums);
            // Spawn the edited creature copies. After the repair step, so the rest of the
            // functor still goes out exactly as the game wrote it.
            if (summonTemplates.Count > 0)
            {
                spell.SpellProperties = RewriteSummons(spell.SpellProperties, summonTemplates)!;
                spell.SpellSuccess = RewriteSummons(spell.SpellSuccess, summonTemplates);
                spell.SpellFail = RewriteSummons(spell.SpellFail, summonTemplates);
            }
            foreach (var (label, value) in new[] {
                ("spell SpellProperties", spell.SpellProperties), ("spell SpellSuccess", spell.SpellSuccess ?? ""),
                ("spell SpellFail", spell.SpellFail ?? "") })
            {
                ValidatePlaceholders(spell.Name, label, value, warnings);
                ValidateStatusReferences(spell.Name, label, value, resolver, warnings, ownStatuses);
            }

            if (string.IsNullOrEmpty(spell.SpellType) && resolver != null && spell.UsingBase != null)
                spell.SpellType = resolver.Resolve(spell.UsingBase, "SpellType") ?? spell.SpellType;

            // A variant follows its container's choice.
            var selfOverride = (container?.EditOriginal ?? spell.EditOriginal)
                && spell.UsingBase != null
                && spell.Name.Equals(spell.UsingBase, StringComparison.OrdinalIgnoreCase);
            if (selfOverride) editedOriginals.Add(spell.Name);

            stats.AppendLine($"new entry \"{spell.Name}\"");
            stats.AppendLine($"type \"SpellData\"");
            stats.AppendLine($"data \"SpellType\" \"{spell.SpellType}\"");
            // An edited original re-declares itself (`using "<self>"`), the form AMP uses to
            // rebalance vanilla spells; a copy points at the original under its own name.
            var spellHasUsing = spell.UsingBase != null
                && (selfOverride || !spell.Name.Equals(spell.UsingBase, StringComparison.OrdinalIgnoreCase));
            if (spellHasUsing)
                stats.AppendLine($"using \"{spell.UsingBase}\"");

            // An edited original whose text was left alone keeps the original handles, which the
            // game translates into every language; writing our copy of two languages under a new
            // handle would blank the rest.
            var keepName = selfOverride && !spell.DisplayNameEdited && !string.IsNullOrEmpty(spell.SourceDisplayNameHandle);
            var keepDesc = selfOverride && !spell.DescriptionEdited && !string.IsNullOrEmpty(spell.SourceDescriptionHandle);
            // Anything else writes its own text, so it must never do that under the source's handle.
            if (!keepName && (string.IsNullOrEmpty(spell.DisplayNameHandle) || SameHandle(spell.DisplayNameHandle, spell.SourceDisplayNameHandle)))
                spell.DisplayNameHandle = HandleGenerator.New();
            if (!keepDesc && (string.IsNullOrEmpty(spell.DescriptionHandle) || SameHandle(spell.DescriptionHandle, spell.SourceDescriptionHandle)))
                spell.DescriptionHandle = HandleGenerator.New();
            var nameHandle = keepName ? spell.SourceDisplayNameHandle! : spell.DisplayNameHandle;
            var descHandle = keepDesc ? spell.SourceDescriptionHandle! : spell.DescriptionHandle;

            stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(nameHandle)}\"");
            stats.AppendLine($"data \"Description\" \"{HandleGenerator.FormatWithVersion(descHandle)}\"");

            void Emit(string key, string? value, bool always)
            {
                if (value == null) return;
                if (always || value.Length > 0)
                    stats.AppendLine($"data \"{key}\" \"{value}\"");
            }
            // With a base, card fields are written even when empty so clearing a field on the card
            // clears it in game instead of inheriting it back. Null fields are not on the card.
            Emit("DescriptionParams", spell.DescriptionParams, spellHasUsing);
            Emit("Icon", string.IsNullOrEmpty(spell.Icon) ? null : spell.Icon, false);
            Emit("Level", spell.Level, spellHasUsing);
            Emit("SpellSchool", spell.SpellSchool, spellHasUsing);
            Emit("UseCosts", spell.UseCosts, spellHasUsing);
            Emit("Cooldown", spell.Cooldown, spellHasUsing);
            Emit("TargetRadius", spell.TargetRadius, spellHasUsing);
            Emit("AreaRadius", spell.AreaRadius, spellHasUsing);
            Emit("SpellRoll", spell.SpellRoll, spellHasUsing);
            Emit("SpellSuccess", spell.SpellSuccess, spellHasUsing);
            Emit("SpellFail", spell.SpellFail, spellHasUsing);
            Emit("SpellProperties", spell.SpellProperties, spellHasUsing);
            Emit("TargetConditions", spell.TargetConditions, spellHasUsing);
            Emit("SpellFlags", spell.SpellFlags, spellHasUsing);

            // Container links of a copy. Inherited through `using`, a copied container would list
            // the original variants and a copied variant would rejoin the original container, so
            // both directions are restated with the copies' names (the way AMP builds item
            // containers). An edited original keeps the links it has.
            if (!selfOverride && spellHasUsing)
            {
                string? Inherited(string key) => spellBase?.GetValueOrDefault(key) is { Length: > 0 } v ? v : null;
                if (spell.Variants.Count > 0)
                    Emit("ContainerSpells", string.Join(";", spell.Variants.Select(v => v.Name)), true);
                if (container != null)
                {
                    Emit("SpellContainerID", container.Name, true);
                    if (Inherited("ContainerSpells") != null) Emit("ContainerSpells", "", true);
                }
                else if (spell.Variants.Count == 0 && Inherited("SpellContainerID") != null)
                {
                    // A variant copied as a spell of its own leaves the original container.
                    Emit("SpellContainerID", "", true);
                    if (Inherited("ContainerSpells") != null) Emit("ContainerSpells", "", true);
                }
                // An upcast copy would otherwise group under the original spell it was cast up from.
                if ((container != null || spell.Variants.Count > 0 || Inherited("SpellContainerID") != null)
                    && Inherited("RootSpellID") != null)
                    Emit("RootSpellID", "", true);
            }

            foreach (var (key, value) in spell.ExtraData)
                stats.AppendLine($"data \"{key}\" \"{value}\"");

            stats.AppendLine();

            if (!keepName) AddLocaEntries(loca, spell.DisplayName, spell.DisplayNameHandle);
            if (!keepDesc) AddLocaEntries(loca, spell.Description, spell.DescriptionHandle);
        }

        // ─── Summoned creature stats ────────────────────
        foreach (var summon in art.Summons)
        {
            if (string.IsNullOrEmpty(summon.UsingBase) || string.IsNullOrEmpty(summon.StatsName)) continue;
            var creatureBase = resolver?.ResolveAll(summon.UsingBase);
            if (resolver != null && !resolver.AllEntries.ContainsKey(summon.UsingBase))
                warnings.Add($"[{art.StatId}] summon '{summon.StatsName}' uses unknown creature stats '{summon.UsingBase}'.");

            stats.AppendLine($"new entry \"{summon.StatsName}\"");
            stats.AppendLine("type \"Character\"");
            stats.AppendLine($"using \"{summon.UsingBase}\"");
            foreach (var (key, value) in summon.Stats)
            {
                var outValue = value ?? "";
                if (key == "DefaultBoosts" && !(creatureBase?.TryGetValue(key, out var inherited) == true && inherited == outValue))
                    outValue = ConditionSchema.NormalizeConditionEnums(BoostMapping.SanitizeBoosts(outValue));
                stats.AppendLine($"data \"{key}\" \"{outValue}\"");
            }
            stats.AppendLine();

            if (summon.DisplayNameEdited)
                AddLocaEntries(loca, summon.DisplayName, summon.DisplayNameHandle);
        }

        // ─── Spell/Status Rename Overrides ─────────────────
        foreach (var (origId, names) in art.SpellRenames)
        {
            if (names.Count == 0) continue;
            // A spell card editing the original already declares this entry; a second
            // declaration would silently replace the card's changes.
            if (editedOriginals.Contains(origId))
            {
                warnings.Add($"[{art.StatId}] rename of spell '{origId}' ignored — the spell card editing it sets its name.");
                continue;
            }
            var handle = HandleGenerator.New();
            // Resolve SpellType from resolver (required for SpellData)
            var spellType = resolver?.Resolve(origId, "SpellType") ?? "Target";
            stats.AppendLine($"new entry \"{origId}\"");
            stats.AppendLine("type \"SpellData\"");
            stats.AppendLine($"data \"SpellType\" \"{spellType}\"");
            stats.AppendLine($"using \"{origId}\"");
            stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(handle)}\"");
            stats.AppendLine();
            AddLocaEntries(loca, names, handle);
        }
        foreach (var (origId, names) in art.StatusRenames)
        {
            if (names.Count == 0) continue;
            if (editedOriginalStatuses.Contains(origId))
            {
                warnings.Add($"[{art.StatId}] rename of status '{origId}' ignored — the status card editing it sets its name.");
                continue;
            }
            var handle = HandleGenerator.New();
            // Resolve StatusType from resolver (required for StatusData)
            var statusType = resolver?.Resolve(origId, "StatusType") ?? "BOOST";
            stats.AppendLine($"new entry \"{origId}\"");
            stats.AppendLine("type \"StatusData\"");
            stats.AppendLine($"data \"StatusType\" \"{statusType}\"");
            stats.AppendLine($"using \"{origId}\"");
            stats.AppendLine($"data \"DisplayName\" \"{HandleGenerator.FormatWithVersion(handle)}\"");
            stats.AppendLine();
            AddLocaEntries(loca, names, handle);
        }

        // ─── Item Localization (stored in RootTemplate, not Stats) ──
        // We still generate loca entries — the RootTemplate LSF will
        // reference these handles for DisplayName/Description.
        AddLocaEntries(loca, art.DisplayName, art.DisplayNameHandle, fillEnglish: false);
        AddLocaEntries(loca, art.Description, art.DescriptionHandle, fillEnglish: false);

        // ─── Icons ──────────────────────────────────────
        Dictionary<string, byte[]>? iconFiles = null;
        if (art.IconMainDdsBase64 != null && art.IconConsoleDdsBase64 != null)
        {
            iconFiles = new Dictionary<string, byte[]>
            {
                [$"GUI/Assets/Tooltips/ItemIcons/{art.StatId}.DDS"] =
                    Convert.FromBase64String(art.IconMainDdsBase64),
                [$"GUI/Assets/ControllerUIIcons/items_png/{art.StatId}.DDS"] =
                    Convert.FromBase64String(art.IconConsoleDdsBase64),
            };
        }

        return new CompileResult
        {
            StatsText = stats.ToString(),
            LocalizationEntries = loca,
            TemplateUuid = art.TemplateUuid,
            ParentTemplateUuid = art.ParentTemplateUuid,
            IconFiles = iconFiles,
            Warnings = warnings,
        };
    }

    private static readonly System.Text.RegularExpressions.Regex UnlockSpellRegex =
        new(@"\bUnlockSpell\(\s*([A-Za-z0-9_]+)", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static string RewriteUnlockSpell(string boosts, IReadOnlyDictionary<string, string> renames) =>
        string.IsNullOrEmpty(boosts) ? boosts
            : UnlockSpellRegex.Replace(boosts, m => renames.TryGetValue(m.Groups[1].Value, out var renamed)
                ? $"UnlockSpell({renamed}" : m.Value);

    private static readonly System.Text.RegularExpressions.Regex SummonRegex =
        new(@"(\bSummon\(\s*)([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})",
            System.Text.RegularExpressions.RegexOptions.Compiled);

    /// <summary>Creature template UUIDs spawned by <c>Summon(…)</c> calls in functor text.</summary>
    public static IEnumerable<string> SummonedTemplates(string? functors) =>
        string.IsNullOrEmpty(functors) ? []
            : SummonRegex.Matches(functors).Select(m => m.Groups[2].Value);

    private static string? RewriteSummons(string? functors, IReadOnlyDictionary<string, string> templates) =>
        string.IsNullOrEmpty(functors) ? functors
            : SummonRegex.Replace(functors, m => templates.TryGetValue(m.Groups[2].Value, out var copy)
                ? m.Groups[1].Value + copy : m.Value);

    /// <summary>Names every summon's Character entry <c>{StatId}_Summon_{n}</c> (idempotent).</summary>
    public static void AssignSummonNames(ArtifactDefinition art)
    {
        var prefix = art.StatId + "_Summon_";
        var taken = new HashSet<string>(
            art.Summons.Select(s => s.StatsName).Where(n => n.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)),
            StringComparer.OrdinalIgnoreCase);
        int n = 1;
        foreach (var s in art.Summons)
        {
            if (s.StatsName.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) continue;
            string name;
            do name = $"{prefix}{n++}"; while (taken.Contains(name));
            taken.Add(name);
            s.StatsName = name;
        }
    }

    /// <summary>
    /// A name the compiler gives copies (<c>{StatId}{kind}{n}</c>) of an artifact other than
    /// <paramref name="statId"/>. A mod's own entry can look the same (AMP has
    /// <c>…_Leeching_Passive_3</c>), so callers also check that the card is a copy of something else.
    /// </summary>
    private static bool IsOtherArtifactsCopyName(string name, string kind, string statId)
    {
        var at = name.LastIndexOf(kind, StringComparison.OrdinalIgnoreCase);
        if (at <= 0 || at + kind.Length == name.Length || !name[(at + kind.Length)..].All(char.IsAsciiDigit)) return false;
        return !name[..at].Equals(statId, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>The first <c>{prefix}{n}</c> from <paramref name="start"/> up not in <paramref name="taken"/>, which it joins.</summary>
    private static string NextFreeName(string prefix, int start, ISet<string> taken)
    {
        string name;
        int n = start;
        do name = $"{prefix}{n++}"; while (taken.Contains(name));
        taken.Add(name);
        return name;
    }

    private static bool SameHandle(string? a, string? b) =>
        !string.IsNullOrEmpty(a) && !string.IsNullOrEmpty(b)
        && HandleGenerator.Parse(a).handle.Equals(HandleGenerator.Parse(b).handle, StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Gives every spell card copied from an existing spell a per-artifact name
    /// (<c>{StatId}_Spell_{n}</c>) that <c>using</c>s the original, and points the item's
    /// SpellsOnEquip at the new names. A card set to edit the original gets its original name
    /// back. Returns original name → name written.
    /// </summary>
    private static Dictionary<string, string> RenameSpellCopies(ArtifactDefinition art, Parsing.StatsResolver? resolver)
    {
        var renames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var taken = new HashSet<string>(art.Spells.Select(s => s.Name), StringComparer.OrdinalIgnoreCase);
        var copyPrefix = art.StatId + "_Spell_";

        for (int i = 0; i < art.Spells.Count; i++)
        {
            var sp = art.Spells[i];
            var currentName = sp.Name;

            if (sp.EditOriginal)
            {
                // Switched from copy to original after a compile had already renamed it (this
                // artifact's compile, or the one of the artifact it was duplicated from).
                if (!string.IsNullOrEmpty(sp.UsingBase)
                    && !currentName.Equals(sp.UsingBase, StringComparison.OrdinalIgnoreCase))
                {
                    sp.Name = sp.UsingBase;
                    renames[currentName] = sp.Name;
                }
                continue;
            }

            var needsRename = !currentName.StartsWith(art.StatId, StringComparison.OrdinalIgnoreCase)
                && (sp.UsingBase == null || sp.UsingBase.Equals(currentName, StringComparison.OrdinalIgnoreCase));
            // A copy another artifact's compile already named (a duplicate of a compiled artifact):
            // renamed for this artifact, still `using` the same original.
            if (!needsRename && !string.IsNullOrEmpty(sp.UsingBase)
                && !sp.UsingBase.Equals(currentName, StringComparison.OrdinalIgnoreCase)
                && IsOtherArtifactsCopyName(currentName, "_Spell_", art.StatId))
            {
                var copyName = NextFreeName(copyPrefix, i + 1, taken);
                renames[currentName] = copyName;
                sp.Name = copyName;
                continue;
            }
            if (!needsRename) continue;

            // Chain `using` only to a spell that exists — `using "Unknown"` is silently dropped.
            var hasRealBase = resolver != null
                ? resolver.AllEntries.ContainsKey(currentName)
                : sp.UsingBase != null;

            var newName = NextFreeName(copyPrefix, i + 1, taken);

            renames[currentName] = newName;
            sp.UsingBase = hasRealBase ? currentName : null;
            sp.Name = newName;

            if (hasRealBase && resolver != null)
            {
                var sourceFields = resolver.ResolveAll(currentName);
                if (SharesHandle(sourceFields, "DisplayName", sp.DisplayNameHandle))
                    sp.DisplayNameHandle = HandleGenerator.New();
                if (SharesHandle(sourceFields, "Description", sp.DescriptionHandle))
                    sp.DescriptionHandle = HandleGenerator.New();
            }
        }

        // Variants follow their container. A copy's variants are named after the container's current
        // name on every compile — the patcher compiles an artifact twice on the same objects, and
        // the second pass has nothing left to rename. An edited original's variants override theirs.
        foreach (var container in art.Spells)
        {
            for (int k = 0; k < container.Variants.Count; k++)
            {
                var v = container.Variants[k];
                var currentName = v.Name;
                if (container.EditOriginal)
                {
                    if (!string.IsNullOrEmpty(v.UsingBase) && !currentName.Equals(v.UsingBase, StringComparison.OrdinalIgnoreCase))
                    {
                        v.Name = v.UsingBase;
                        renames[currentName] = v.Name;
                    }
                    continue;
                }

                var target = $"{container.Name}_{k + 1}";
                if (currentName.Equals(target, StringComparison.OrdinalIgnoreCase)) continue;
                var original = v.UsingBase ?? currentName;
                var hasRealBase = resolver != null ? resolver.AllEntries.ContainsKey(original) : v.UsingBase != null;
                renames[currentName] = target;
                v.UsingBase = hasRealBase ? original : null;
                v.Name = target;
                if (hasRealBase && resolver != null)
                {
                    var sourceFields = resolver.ResolveAll(original);
                    if (SharesHandle(sourceFields, "DisplayName", v.DisplayNameHandle))
                        v.DisplayNameHandle = HandleGenerator.New();
                    if (SharesHandle(sourceFields, "Description", v.DescriptionHandle))
                        v.DescriptionHandle = HandleGenerator.New();
                }
            }
        }

        if (renames.Count > 0 && !string.IsNullOrEmpty(art.SpellsOnEquip))
        {
            art.SpellsOnEquip = string.Join(";",
                art.SpellsOnEquip.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                    .Select(s => renames.TryGetValue(s, out var renamed) ? renamed : s));
        }
        return renames;
    }

    /// <summary>
    /// Gives every status card that is not an edited original a name of this artifact
    /// (<c>{StatId}_Status_{n}</c>). A card copied from a status <c>using</c>s it; a card made from
    /// scratch has no base. A name another artifact's prefix (a duplicated artifact) is renamed too,
    /// or the two artifacts would declare the same status. Returns old name → name written.
    /// </summary>
    internal static Dictionary<string, string> RenameStatusCopies(ArtifactDefinition art, Parsing.StatsResolver? resolver)
    {
        var renames = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var prefix = art.StatId + "_Status_";
        var taken = new HashSet<string>(art.Statuses.Select(s => s.Name), StringComparer.OrdinalIgnoreCase);

        foreach (var st in art.Statuses)
        {
            var current = st.Name;
            if (st.EditOriginal && !string.IsNullOrEmpty(st.UsingBase))
            {
                // Switched from copy to original after a compile had already renamed it.
                if (!current.Equals(st.UsingBase, StringComparison.OrdinalIgnoreCase))
                {
                    st.Name = st.UsingBase;
                    renames[current] = st.Name;
                }
                continue;
            }
            if (current.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) continue;

            // A fresh copy still carries the original's name; point `using` at it when it exists.
            if (st.UsingBase != null && st.UsingBase.Equals(current, StringComparison.OrdinalIgnoreCase)
                && resolver != null && !resolver.AllEntries.ContainsKey(current))
                st.UsingBase = null;

            var name = StatusCloner.NextName(art, taken);
            taken.Add(name);
            renames[current] = name;
            if (st.StackId != null && st.StackId.Equals(current, StringComparison.OrdinalIgnoreCase) && st.UsingBase == null)
                st.StackId = name;
            st.Name = name;
        }
        return renames;
    }

    /// <summary>
    /// StatusData functor and condition fields that are not on the status card (Modifiers.txt, plus
    /// Conditions and TargetConditions, which the game's and AMP's statuses use as well).
    /// </summary>
    private static readonly string[] InheritedStatusTextFields =
    [
        "OnApplyConditions", "OnApplyRoll", "OnApplySuccess", "OnApplyFail",
        "OnTickRoll", "OnTickSuccess", "OnTickFail",
        "OnRemoveRoll", "OnRemoveSuccess", "OnRemoveFail",
        "OnRollsFailed", "OnSuccess", "Conditions", "TargetConditions",
    ];

    /// <summary>Calls whose arguments name a status (surveyed from the game's and AMP's stats).</summary>
    private static readonly HashSet<string> StatusArgumentCalls = new(StringComparer.Ordinal)
    {
        "ApplyStatus", "ApplyEquipmentStatus", "RemoveStatus", "RemoveUniqueStatus", "HasStatus", "HasAnyStatus",
        "StatusImmunity", "IsImmuneToStatus", "StatusId", "StatusIdIs", "SetStatusDuration", "GetStatusDuration",
        "StatusDurationEqualOrMoreThan", "StatusDurationLessThan", "DownedStatus", "RemoveAuraByChildStatus",
        "MaximumHighStackableStatus", "MaximumLowStackableStatus", "MaximumHigherStackableStatus",
        "Summon", "SummonInInventory", "Spawn",
    };

    /// <summary>
    /// Points every mention of a renamed status in this artifact at its new name: StatusOnEquip,
    /// and the functors and conditions of the item, its passives, spell cards and status cards. A
    /// name counts where a status goes — an argument of a status call (<c>ApplyStatus(SELF,BLESS,…)</c>,
    /// <c>HasStatus('BLESS')</c>) or a <c>BLESS.Duration</c> — and not where a tag of the same name
    /// does (<c>Tag(COMPREHEND_LANGUAGES)</c>).
    /// </summary>
    internal static void RewriteStatusReferences(ArtifactDefinition art, IReadOnlyDictionary<string, string> renames)
    {
        string? Rewrite(string? v) => RewriteStatusText(v, renames);

        art.StatusOnEquip = string.Join(";", (art.StatusOnEquip ?? "")
            .Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(n => renames.TryGetValue(n, out var renamed) ? renamed : n));
        art.Boosts = Rewrite(art.Boosts) ?? "";
        art.DefaultBoosts = Rewrite(art.DefaultBoosts);
        art.BoostsOnEquipMainHand = Rewrite(art.BoostsOnEquipMainHand);
        art.BoostsOnEquipOffHand = Rewrite(art.BoostsOnEquipOffHand);
        for (int i = 0; i < art.RemovedStatuses.Count; i++)
            if (renames.TryGetValue(art.RemovedStatuses[i], out var removed)) art.RemovedStatuses[i] = removed;
        foreach (var p in art.Passives)
        {
            p.Boosts = Rewrite(p.Boosts) ?? "";
            p.BoostConditions = Rewrite(p.BoostConditions) ?? "";
            p.StatsFunctors = Rewrite(p.StatsFunctors) ?? "";
            p.Conditions = Rewrite(p.Conditions) ?? "";
        }
        foreach (var sp in art.Spells.SelectMany(s => s.WithVariants()))
        {
            sp.SpellProperties = Rewrite(sp.SpellProperties) ?? "";
            sp.SpellSuccess = Rewrite(sp.SpellSuccess);
            sp.SpellFail = Rewrite(sp.SpellFail);
            sp.TargetConditions = Rewrite(sp.TargetConditions) ?? "";
        }
        foreach (var st in art.Statuses)
        {
            st.Boosts = Rewrite(st.Boosts) ?? "";
            st.TickFunctors = Rewrite(st.TickFunctors);
            st.OnApplyFunctors = Rewrite(st.OnApplyFunctors);
            st.OnRemoveFunctors = Rewrite(st.OnRemoveFunctors);
            st.RemoveConditions = Rewrite(st.RemoveConditions);
            st.AuraStatuses = Rewrite(st.AuraStatuses);
        }
    }

    /// <summary>One field's text with renamed statuses pointed at their new names (see <see cref="RewriteStatusReferences"/>).</summary>
    internal static string? RewriteStatusText(string? text, IReadOnlyDictionary<string, string> renames)
    {
        if (string.IsNullOrEmpty(text) || renames.Count == 0) return text;
        var pattern = new System.Text.RegularExpressions.Regex(
            @"(?<![A-Za-z0-9_])(" + string.Join("|", renames.Keys.OrderByDescending(k => k.Length).Select(System.Text.RegularExpressions.Regex.Escape)) + @")(?![A-Za-z0-9_])",
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        return pattern.Replace(text, m => renames.TryGetValue(m.Value, out var n) && IsStatusPosition(text, m.Index, m.Length) ? n : m.Value);
    }

    /// <summary>The name at <paramref name="index"/> is an argument of a status call, or a status's <c>.Duration</c>.</summary>
    private static bool IsStatusPosition(string text, int index, int length)
    {
        if (string.CompareOrdinal(text, index + length, ".Duration", 0, 9) == 0) return true;
        int depth = 0, j = index - 1;
        for (; j >= 0; j--)
        {
            if (text[j] == ')') depth++;
            else if (text[j] == '(' && depth-- == 0) break;
        }
        if (j < 0) return false;
        int k = j;
        while (k > 0 && (char.IsLetterOrDigit(text[k - 1]) || text[k - 1] == '_')) k--;
        return StatusArgumentCalls.Contains(text[k..j]);
    }

    /// <summary>
    /// Generate localization XML content for a specific language.
    /// </summary>
    public static string GenerateLocaXml(IReadOnlyList<(string handle, string xmlText)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        sb.AppendLine("<contentList>");
        foreach (var (handle, text) in entries)
        {
            sb.AppendLine($"  <content contentuid=\"{handle}\" version=\"1\">{text}</content>");
        }
        sb.AppendLine("</contentList>");
        return sb.ToString();
    }

    /// <summary>
    /// Loca entries for a handle, one per language with text. The game falls back to English for a
    /// language a handle has no text in, so a text written only in another language (a status named
    /// in Russian alone) also goes out as the English one — or every other language would show
    /// nothing. Not for a handle that may be the game's (the item's own name): its English exists.
    /// </summary>
    private static void AddLocaEntries(
        Dictionary<string, List<(string, string)>> loca,
        Dictionary<string, string> texts,
        string handle,
        bool fillEnglish = true)
    {
        if (string.IsNullOrEmpty(handle)) return;

        foreach (var (lang, bbcode) in texts)
        {
            if (string.IsNullOrEmpty(bbcode)) continue;
            Add(lang, bbcode);
        }
        if (fillEnglish && string.IsNullOrEmpty(texts.GetValueOrDefault("en")) && EnglishFallback(texts) is { } fallback)
            Add("en", fallback);

        void Add(string lang, string bbcode)
        {
            if (!loca.ContainsKey(lang))
                loca[lang] = [];
            loca[lang].Add((handle, BbCode.ToBg3Xml(bbcode)));
        }
    }

    /// <summary>The text to show as English when there is none: Russian first, else any language's.</summary>
    internal static string? EnglishFallback(Dictionary<string, string> texts) =>
        !string.IsNullOrEmpty(texts.GetValueOrDefault("ru")) ? texts["ru"]
            : texts.OrderBy(t => t.Key, StringComparer.Ordinal).Select(t => t.Value).FirstOrDefault(v => !string.IsNullOrEmpty(v));
}
